// Market 2 — Professional & market intelligence platforms.
// THE market our flagship competes in. Deliberately NOT forced into the consumer
// one-trick machine: this market runs a different loop, named below.
//
// Evidence note: Palantir's numbers are unusually hard because the UK G-Cloud 14
// price sheet is public. Most others publish no rate card, so seat prices are
// third-party estimates and are flagged per row.

import type { MarketTeardownData } from './marketTeardown';

export type Confidence = 'confirmed' | 'estimate' | 'none';

export type MoatArchetype = 'semantic-lock-in' | 'permissions-graph' | 'licensed-data' | 'deployability' | 'workflow-shape';

export type EnterpriseSpecimen = {
  rank: number;
  name: string;
  job: string;
  /** Headline pricing, with confidence. */
  pricing: string;
  pricingConfidence: Confidence;
  scale: string;
  surfaces: string;
  moat: string;
  moatArchetype: MoatArchetype;
  weakness: string;
  lesson: string;
  /** 0-100 durability of the moat. */
  durability: number;
  verdict: string;
};

export type EnterpriseMachineStep = {
  index: number;
  name: string;
  detail: string;
  exemplars: string;
};

export type UnservedGap = {
  gap: string;
  evidence: string;
  ourPosition: string;
  /** Can we actually serve it today? */
  weCanServe: 'yes' | 'partly' | 'no';
};

export const moatArchetypeLabel: Record<MoatArchetype, string> = {
  'semantic-lock-in': 'semantic lock-in',
  'permissions-graph': 'permissions graph',
  'licensed-data': 'licensed data',
  deployability: 'deployability',
  'workflow-shape': 'workflow shape',
};

export const professionalIntelligenceMarket: MarketTeardownData = {
  generatedAt: '2026-08-03T00:00:00-04:00',
  headline: 'Professional & Market Intelligence',
  marketLabel: 'market 2',
  machineTitle: "This market's machine — eight steps",
  machineNote: 'Not the consumer loop. No virality, no watermark, no streak. TRUST → EMBED → GOVERN → ACCRETE → EXPAND → ESCALATE — and step 8 is eating step 1.',
  lede:
    'The market our flagship actually competes in. Twenty-three platforms torn down, from Bloomberg at ~$32K/seat to Feedly at ~$19K for a whole team. This market does NOT run the consumer machine — there is no viral loop, no watermark, no streak. It runs on substrate ownership, governed deployability, and who is trusted to act unattended.',
  thesis:
    'The moat was never the data — it was being the number people CITE. PitchBook\'s valuation, Similarweb\'s traffic estimate, Bloomberg\'s price. Citational authority survives worse data, higher prices and hostile renewals for a remarkably long time — and it is exactly what an LLM strips away, because when an agent answers the question the user never sees whose number it was. Every incumbent here is racing into MCP integrations that dissolve the only moat they had. The defensible counter-move is the opposite of what they are all doing: make provenance the product — signed, timestamped, per-claim lineage an agent must attribute in order to use. Be the source the model is REQUIRED to cite, not the source it silently absorbs.',

  machine: [
    {
      index: 1,
      name: 'Land via a modelling engagement',
      detail: 'Give away implementation to get the customer\'s business logic encoded in your model before price is negotiated. After that the schema, not the contract, is the lock-in.',
      exemplars: 'Palantir AIP Bootcamp — "0 to use case in 5 days", ~75% attendee→contract conversion (est.)',
    },
    {
      index: 2,
      name: 'Own an un-re-derivable substrate',
      detail: 'An ontology, a permissions graph, a licensed firehose, or an accreditation — the one asset a competitor cannot clone in a quarter.',
      exemplars: 'Palantir Ontology · Glean ACL graph · Quid 2PB licensed feeds',
    },
    {
      index: 3,
      name: 'Enforce permissions in the architecture',
      detail: 'ACLs ingested with content and checked OUTSIDE the model at retrieval time — never in the prompt. This is what makes an answer engine deployable company-wide.',
      exemplars: 'Glean — per-document/field/sentence enforcement, real-time ACL delta-sync',
    },
    {
      index: 4,
      name: 'Ship in the artifact shape they already produce',
      detail: 'Chat is a demo; the analyst\'s existing deliverable is the product. Auditable, diffable, pasteable into the deal file.',
      exemplars: 'Hebbia Matrix — documents × questions grid with cited cells',
    },
    {
      index: 5,
      name: 'Make deployability the architecture',
      detail: 'Air-gapped, DDIL and edge operation designed in from the first commit — the one capability cloud-native competitors structurally cannot retrofit.',
      exemplars: 'Palantir Apollo (FedRAMP High, IL5/IL6) · Primer (air-gapped, DDIL, tactical edge)',
    },
    {
      index: 6,
      name: 'Monetize governance separately',
      detail: 'Price the answer at scale to get into every department; sell SCIM, audit logs and retention controls to the CISO at a step change.',
      exemplars: 'Perplexity — $400/seat/yr Pro vs $3,250 Max, where audit logs + SCIM live',
    },
    {
      index: 7,
      name: 'Draw the retrieved / generated boundary',
      detail: 'Make an explicit, product-visible line between facts that are RETRIEVED and language that is GENERATED. Never let the model produce a number it could have looked up. Four vendors converged on this independently — it is the architectural answer to hallucination in regulated buying.',
      exemplars: 'Kensho "deterministic vs adaptive retrieval" · Rogo computes multiples from real data pulls, never model arithmetic · Brightwave sentence-level attribution · AlphaSense source-linked auditability',
    },
    {
      index: 8,
      name: 'Escalate price under lock-in — and the trap',
      detail: 'The terminal step, and the market\'s original sin. Bloomberg +60% since 2010. PitchBook 8-14%/yr with 3-year caps at 3-4%. Meltwater\'s 60-day auto-renewal. Intel 471\'s "standard 7% uplift". THE LOAD-BEARING OBSERVATION: step 8 is eating step 1. PitchBook lost ~12,000 licensed users while growing revenue 8.6%; Similarweb NRR fell to 98% and its $100K+ cohort from 112% to 103%; CB Insights is contracting; Dataminr reset $4.1B → ~$1B; Cision sits at Caa1. The incumbents have shifted from WINNING WORK to HARVESTING LOCK-IN — precisely the condition that invites displacement.',
      exemplars: 'PitchBook · Meltwater · Bloomberg · Intel 471',
    },
  ] as EnterpriseMachineStep[],

  specimens: [
    {
      rank: 1,
      name: 'Palantir (Foundry + AIP)',
      job: 'Operational decision system, not a search box. Ingest everything, model it as an Ontology of objects/links/actions, then drive analyst workflows and write-back actions in one loop.',
      pricing: 'UK G-Cloud list (public): PT-ORG single-org licence £3,000,000/yr; PF-CORE £66,000 per server core/yr; FDE services £150,000 per person per quarter; pilots £50K–£500K. Typical first commercial contract $500K–$2M/yr.',
      pricingConfidence: 'confirmed',
      scale: 'FY2025 revenue $4.48B; Q1 2026 +85% YoY ($1.63B), US commercial +133%; 1,007 TTM customers.',
      surfaces: 'Web workspace (Contour, Quiver, Workshop, Code Workbook), Ontology SDK, REST/ODBC, AIP Assist sidebar in every app, Apollo deploy to cloud/on-prem/air-gapped/edge.',
      moat: 'The Ontology IS the lock-in — business logic, permissions and actions encoded in their object model. Plus FedRAMP High + DoD IL5/IL6, and FedStart which lets other vendors ride that accreditation.',
      moatArchetype: 'semantic-lock-in',
      weakness: 'Reviewers cite heavy effort to get value, fiddly UI, performance at volume, and opaque pricing with 2–3× variance between comparable deals. Reputational risk (ICE contracts, internal revolt) is now a procurement risk.',
      lesson: 'Sell the modelling engagement, not the software. Whoever owns the semantic model owns the account.',
      durability: 95,
      verdict: 'The most defensible platform in the set — ontology lock-in plus an accreditation moat that compounds via FedStart.',
    },
    {
      rank: 2,
      name: 'Glean',
      job: 'Enterprise-wide Work AI: find anything across every SaaS app the employee is permitted to see, then act on it via assistants and agents.',
      pricing: 'No public rate card. ~$50/user/mo base + ~$15 AI add-on + consumption credits (est.); ~100-seat minimum ≈ $60K/yr ACV floor. Initial contracts $100K–$500K/yr; F500 >$5M.',
      pricingConfidence: 'estimate',
      scale: 'ARR $300M (May 2026), 3× in 15 months. ~$768M raised, $7.2B valuation. 85%+ of customers use it across 5+ departments.',
      surfaces: 'Broadest in the set — web, Mac/Windows desktop, iOS/Android, browser extension (all four browsers), Slack, Teams, Jira, Glean Apps + APIs, with context carrying across surfaces.',
      moat: 'The permissions graph, not the LLM. Per-app ACL mirroring across Confluence, Slack, Salesforce, GitHub — multi-year work competitors skip. Content stays in source; only vectors + metadata cached.',
      moatArchetype: 'permissions-graph',
      weakness: 'Inconsistent relevance (users still verify in the source app), limited ranking tuning, hallucination, unintuitive UI, hard setup at scale. Real threat: Microsoft Copilot bundling.',
      lesson: 'Enforce permissions in the retrieval architecture, never in the prompt — ingest each document\'s ACL with its content and check it outside the model.',
      durability: 82,
      verdict: 'Strongest growth in the set; the ACL graph is a genuine multi-year moat, but Copilot bundling is an existential overhang.',
    },
    {
      rank: 3,
      name: 'Perplexity (Enterprise / Finance)',
      job: 'Cited answers over the live web plus internal files; Finance narrows to equity research — quotes, filings, transcripts, live earnings calls.',
      pricing: 'Most transparent here: Enterprise Pro $40/seat/mo ($400/yr); Enterprise Max $325/seat/mo ($3,250/yr); US federal $0.25 per agency for 15 months under GSA OneGov. Sonar API metered.',
      pricingConfidence: 'confirmed',
      scale: 'ARR $450M (Mar 2026) from $100M a year earlier; ~$22.6B valuation; 100M+ MAU. Revenue jumped ~50% in one month after killing advertising entirely.',
      surfaces: 'Web, mobile, Comet AI browser (free worldwide Oct 2025), Finance dashboard, Earnings Hub with live in-call transcription, Portfolio (Plaid), Spaces, Sonar API.',
      moat: 'Licensed real-time data, not model quality — SEC/EDGAR, FactSet, S&P Global, Morningstar, LSEG, Quartr, Fiscal.ai. Plus a consumer funnel feeding enterprise at 1/10th Hebbia\'s seat price.',
      moatArchetype: 'licensed-data',
      weakness: 'Litigation is the headline risk — Dow Jones/News Corp, Britannica/Merriam-Webster (incl. trademark claims over hallucinated attribution), NYT and BBC C&Ds. No permissions graph, no accreditation, thin switching cost at $40/seat. Governance paywalled at an 8× step.',
      lesson: 'Price the answer at consumer scale and monetize governance separately — but secure content licences before the lawsuits price them for you.',
      durability: 68,
      verdict: 'Fastest commercial motion, weakest structural moat — no ACL graph, no accreditation, and an unresolved copyright overhang.',
    },
    {
      rank: 4,
      name: 'Primer.ai',
      job: 'Turn overwhelming multilingual, multimodal information into structured, traceable, mission-ready intelligence for defense and intelligence analysts.',
      pricing: 'No public pricing; government-contract and prime-mediated licensing.',
      pricingConfidence: 'none',
      scale: '~$14.5M revenue (est.) on $237M raised, ~124 staff — capital efficiency looks poor.',
      surfaces: 'Web analyst workspace, Primer Command (entities, narratives, events, maps, timelines in one UI), Primer API, direct C2 integration, tactical edge clients.',
      moat: 'Deployability as a stated design principle — customer-hosted, air-gapped, DDIL, tactical edge. Channel moat via Amentum, GDIT and Palantir as partners.',
      moatArchetype: 'deployability',
      weakness: 'Squeezed from both sides: Palantir above (full mission platform, and simultaneously a listed partner), frontier labs below (CDAO now buys OpenAI/Anthropic/Google/xAI directly at $200M each). Almost no public user reviews; repeated repositioning suggests PMF search.',
      lesson: 'Make deployability the architecture, not a config flag — it is what keeps you in the room when the frontier labs arrive with better models.',
      durability: 55,
      verdict: 'Right moat, wrong position — deployability is genuinely defensible but Primer is a capability inside someone else\'s program.',
    },
    {
      rank: 5,
      name: 'Hebbia',
      job: 'The AI analyst for high-stakes document work — answer hundreds of questions across thousands of documents, every cell traceable to a source line.',
      pricing: 'No public card. ~$10,000/seat/yr Professional, ~$3,000–3,500 Lite (est.), benchmarked deliberately against a Bloomberg Terminal seat. No free trial.',
      pricingConfidence: 'estimate',
      scale: '$13M ARR (Jun 2024, stale — no 2026 figure disclosed); $161M raised at $700M. Claims $30T AUM of client firms, 1.5B pages processed.',
      surfaces: 'Matrix — a spreadsheet grid where documents are rows, questions are columns, agent outputs are cited cells. Plus Matrix API + MCP, SharePoint/Excel/FactSet connectors.',
      moat: 'Workflow shape + citation discipline. Encode the firm\'s process once and it runs continuously. ISO/IEC 42001 AI-management certification is a rare, real differentiator.',
      moatArchetype: 'workflow-shape',
      weakness: 'The most copyable moat in the set — commoditization risk as context windows expand. No chat history, limited customization, and cannot export to Word or PDF, which is severe for a product whose output is a deliverable.',
      lesson: 'Ship the answer in the shape of the artifact the professional already produces. Chat is a demo; the grid is a deliverable.',
      durability: 52,
      verdict: 'Best single UI idea in the market attached to the weakest moat; ARR an order of magnitude below Glean at comparable vintage.',
    },
    {
      rank: 6,
      name: 'Quid (NetBase Quid)',
      job: 'Consumer and market intelligence — what people are saying, why, and what is next, across social, news, broadcast, reviews, forums and patents.',
      pricing: 'Entry ~$4,995/quarter (~$20K/yr, est.); no public tier structure.',
      pricingConfidence: 'estimate',
      scale: '~$64.5M revenue (est.); >$100M raised historically; formed by the 2020 NetBase + Quid merger.',
      surfaces: 'Quid Terminal, Discover, Monitor, plus the Feb 2026 Q Platform / Q Agents launch. Web dashboards, API, real-time alerts.',
      moat: 'The data moat is the whole business — >2PB ingested: 200M+ social posts/day, 1M+ articles/day, 1M+ broadcast transcripts/day, 90K+ patents weekly, all under direct licensed partnerships with platforms that keep closing their APIs.',
      moatArchetype: 'licensed-data',
      weakness: 'Steep learning curve cited repeatedly, high cost, questioned sentiment accuracy, outdated UI. Strategically a legacy analytics vendor bolting agents onto a 20-year NLP stack; the analysis layer is now LLM-commoditizable.',
      lesson: 'Own licensed access to data that is getting harder to get — the analysis layer can be rebuilt any time, the pipes cannot.',
      durability: 58,
      verdict: 'Durable pipes, commoditizing product. The Q Platform launch reads as a defensive re-platform.',
    },
  {
      rank: 7,
      name: 'Bloomberg Terminal',
      job: 'The trading floor\'s nervous system — real-time pricing, news, analytics, execution AND counterparty communication in one pane.',
      pricing: '~$31,980/seat/yr single terminal, ~$28,320 multi-terminal (est. — Bloomberg publishes nothing). ~6.5% renewal uplift in 2025. Flat all-in bundle, deliberately un-unbundleable.',
      pricingConfidence: 'estimate',
      scale: '~325,000 subscribers (2022, carried forward); Terminal is >85% of Bloomberg LP revenue (~$12.5B est.).',
      surfaces: 'Native terminal + dedicated keyboard, Bloomberg Anywhere + B-Unit biometric fob, mobile, Excel add-in (BDP/BDH/BDS), Instant Bloomberg chat, Vision Pro app.',
      moat: 'THE MOAT IS THE CONVERSATION, NOT THE DATA. Counterparties negotiate and execute inside IB chat; a quote becomes a binding order that routes to settlement. Leaving IB drops you out of the liquidity pool — and IB is an archived, surveillable channel compliance already accepts.',
      moatArchetype: 'semantic-lock-in',
      weakness: '1980s orange-on-black UI, near-zero mouse affordance, months to proficiency, weak mobile, slow AI integration. Price raised ~60% over 16 years while growing the base — inelastic demand enforced by lock-in, not re-won each year.',
      lesson: 'Own the transactional communication channel BETWEEN two customers, not the content one customer reads. That is the only moat nobody has cracked in 40 years.',
      durability: 97,
      verdict: 'The most durable moat in any market we have studied — a two-sided transaction network disguised as a data terminal.',
    },
    {
      rank: 8,
      name: 'AlphaSense',
      job: 'AI search and agentic research across a curated corpus of filings, transcripts, broker research and expert calls — plus the customer\'s own internal documents.',
      pricing: '~$10,000–20,000/seat/yr enterprise; $40,000+/seat with expert-call transcripts (est.). Median observed contract ~$18,375/yr; ARR per customer grew $28K → $66K in under 3 years.',
      pricingConfidence: 'estimate',
      scale: 'ARR $600M+ (Q1 2026), $350M raised at $7.5B valuation (Jun 2026). 7,000+ enterprises; ~90% of S&P 100. Acquired Tegus for $930M.',
      surfaces: 'Web workspace, browser extension/web clipper, TWO Excel add-ins, Microsoft AppSource listing, mobile, alerts and scheduled digests, public developer API, Slack/Salesforce integrations.',
      moat: 'Exclusive content bought not built — 500M+ premium documents, 200,000+ expert transcripts, 4,500 Canalyst models. Plus Enterprise Intelligence: once a firm indexes its OWN research into AlphaSense, switching means re-indexing institutional memory.',
      moatArchetype: 'licensed-data',
      weakness: 'Price opacity is the #1 complaint; "noisy search results" is the top functional gripe; a Gartner review flagged financials as "frequently incomplete, stale, or has errors". Structurally SUPPLEMENTARY to Bloomberg/FactSet — which makes it a budget-cut candidate in a downturn while the Terminal is not.',
      lesson: 'Buy the corpus, then get the customer\'s own documents into your index. The second is free and stickier than the $930M one.',
      durability: 84,
      verdict: 'Best-funded content roll-up in the category; the leased half of the moat is the risk.',
    },
    {
      rank: 9,
      name: 'Recorded Future (Mastercard)',
      job: 'One queryable index of everything known about an indicator, actor, vulnerability or company — so CTI triage stops being manual OSINT.',
      pricing: 'Median observed contract $70,287/yr across 46 purchases, range $27K–$173K (vendor guides claim $100–500K — the transaction data says otherwise). US Cyber Command awarded $50M.',
      pricingConfidence: 'estimate',
      scale: 'Acquired by Mastercard for $2.65B (closed Dec 2024), from Insight Partners at $780M in 2019. 1,900+ clients, governments of 45 countries, >50% of the Fortune 100.',
      surfaces: 'Intelligence Cloud web workspace, FREE browser extension (Express), API-first with 100+ integrations, free Collective Insights ingestion API, Slack/Teams, Recorded Future University (certification), The Record (owned publication).',
      moat: 'The graph, not the feed — 1M+ sources dynamically linked. Post-acquisition it gained Mastercard payments-network telemetry: a collection source structurally unbuyable by any CTI competitor.',
      moatArchetype: 'licensed-data',
      weakness: 'Cost is complaint #1. "Overwhelming data volume, requires tuning to reduce noise" — alert fatigue pushed onto the customer. Critically: OPAQUE SCORING — reviewers cannot audit why an entity scored what it scored. Provenance-of-source is not provenance-of-judgment.',
      lesson: 'Give away the surface in the analyst\'s click-path (free extension) and the ingestion pipe (free API); charge for the graph. Lock-in built from the customer\'s OWN telemetry, not contract terms.',
      durability: 88,
      verdict: 'Bought a moat nobody can rent. But its scoring opacity is precisely the gap a provenance-first challenger attacks.',
    },
    {
      rank: 10,
      name: 'Dataminr',
      job: 'Be FIRST to tell you something is happening — physical event, breaking news, cyber incident — minutes before wire services. The job is latency, not depth.',
      pricing: 'AWS Marketplace public list: $65,000/yr per Pulse module (Corp Risk, Brand Risk, Cyber Risk) — modules stack, they do not bundle. Median observed contract $22,000/yr, range $15K–$62.5K.',
      pricingConfidence: 'confirmed',
      scale: '$475M raised at $4.1B (2021); ~$200M ARR (est.). But secondary-market valuation reportedly near $1.0B — a ~75% markdown — plus 20% layoffs (2023) and two consecutive convertible/debt rounds in 2025.',
      surfaces: 'Web app, iPhone/iPad/Android (a genuine differentiator — physical-security users are not at a desk), Slack, Teams, Pulse Cyber API into SOAR/SIEM, developer portal.',
      moat: 'RENTED. Privileged unfiltered access to the full X/Twitter firehose while competitors get pre-filtered subsets. Everything since (100K→1M sources, ReGenAI, Intel Agents) is expensive relocation of the moat from access to inference.',
      moatArchetype: 'licensed-data',
      weakness: 'Noise scales with event density — the product degrades exactly when you need it most. False-positive control is outsourced to human account managers, a services answer to a product problem. Serious surveillance-ethics exposure (BLM protest monitoring, against X\'s own terms).',
      lesson: 'A moat you rent is a moat someone else can drain. If your differentiation is a licence, you are one renegotiation from commodity.',
      durability: 45,
      verdict: 'The clearest cautionary tale in the study — a $4.1B valuation built on someone else\'s contract, now marked down ~75%.',
    },
    {
      rank: 11,
      name: 'Feedly (Threat Intelligence)',
      job: 'Kill the analyst\'s manual collection loop — stop reading 200 sources to find the 5 that matter, and get a draft report with citations out the other end.',
      pricing: '~$19,200/yr Standard, ~$38,400 Advanced (est.). Critically: WHOLE-TEAM ACCESS, no per-seat charge. Meters on AI Feeds (50/100) and Agents instead.',
      pricingConfidence: 'estimate',
      scale: '400+ security teams. Remarkably, ~$1.5M ever raised and ~66 employees — competing against a Mastercard subsidiary.',
      surfaces: 'Web workspace, AI Feeds, Ask AI + Report Builder, Slack/Teams, STIX 2.1 API, OpenCTI/XSOAR/MISP/Sentinel integrations, and an early first-class Threat Graph MCP server.',
      moat: 'No proprietary collection at all — it reads the same 10,000+ open sources anyone can. The moat is the EXTRACTION layer: 1,000+ AI models building a Threat Graph (800+ actors, 300K+ CVEs, 500K+ IoCs). Plus a price-point moat at ~1/12th of Intel 471.',
      moatArchetype: 'workflow-shape',
      weakness: 'Coverage ceiling — open-source-first, no HUMINT, no closed-forum access. A complement to Intel 471/Flashpoint, not a substitute. No published precision benchmark for models whose whole value proposition is filtering.',
      lesson: 'WHEN YOU CANNOT OWN THE DATA, OWN THE TRACEABILITY. Feedly spends nothing on collection and is praised for transparent citation, while a $2.65B incumbent is criticized for opaque scoring. And: meter on feeds/agents, not seats — per-seat pricing taxes the exact behaviour an intelligence product needs.',
      durability: 62,
      verdict: 'The most important specimen for us — proves verifiability beats exclusivity, on almost no capital.',
    },
    {
      rank: 12,
      name: 'Intel 471',
      job: 'Adversary intelligence at the ACTOR level — who they are, what they are building, what they will hit next. For CTI teams that have outgrown feeds and want attribution.',
      pricing: 'Median observed contract $240,000/yr, range $160K–$249K — the most expensive in the study, ~3.4x Recorded Future\'s median. Thoma Bravo completed a strategic investment.',
      pricingConfidence: 'estimate',
      scale: '$55.7M raised. Acquired Cyborg Security (2024), which grew the threat-hunting customer base 65% in year one.',
      surfaces: 'TITAN platform, RESTful API, alerting/keyword watchers, CU-GIR-mapped structured intelligence, HUNTER threat-hunting content packs.',
      moat: 'HUMINT — human sources inside closed criminal communities, structured against a formal intelligence-requirements framework (CU-GIR). The framework is the quiet moat: it turns artisanal human output into a subscribable, auditable product.',
      moatArchetype: 'deployability',
      weakness: 'Price. Deep-but-narrow by construction — HUMINT does not scale linearly. Commonly run ALONGSIDE Recorded Future rather than instead of it.',
      lesson: 'Depth commands a premium breadth cannot. If you cannot win on coverage, win on something structurally unscrapable — and let the incumbent be your distribution partner rather than your competitor.',
      durability: 80,
      verdict: 'Charges 3.4x the market leader while being its complement — the clearest proof that judgment outprices volume.',
    },
    {
      rank: 13,
      name: 'Rogo',
      job: 'Do the associate\'s work — comps, precedent transactions, CIM generation, data-room diligence, model audits — and emit the actual deliverable (.xlsx, .pptx, .docx).',
      pricing: '~$3,300/seat/yr (est., and inconsistent with other disclosures — treat as soft). Multi-year contracts, single-tenant deployment, compliance certs bundled.',
      pricingConfidence: 'estimate',
      scale: 'Revenue $2M (2024) → $15M+ (2025). Series D $160M led by Kleiner Perkins; >$300M total; $750M post at Series C. 35,000+ professionals at 250+ institutions. Rothschild, Jefferies, Lazard, Moelis, Nomura.',
      surfaces: 'Chat, AI table interface, Excel/PowerPoint/Word integrations, workflow templates, Felix (agentic deal execution), firm data-warehouse connectivity.',
      moat: 'Office-artifact lock-in plus a compliance wall — SOC 2, ISO/IEC 27001, ISO/IEC 42001 (AI management), GDPR, EU AI Act, single-tenant, no training on customer data. ISO 42001 is a procurement gate most startups cannot clear.',
      moatArchetype: 'workflow-shape',
      weakness: 'Model dependency on OpenAI/Google. Incumbent retaliation risk — S&P/FactSet/Bloomberg can bundle at marginal cost, and Rogo pays those same vendors for data. Practitioner skepticism of AI copilots in deal work is high.',
      lesson: 'Never let the model do arithmetic it could do with a data pull. And ship the DELIVERABLE format — banking runs on .xlsx and .pptx; a chat response gets copy-pasted out of and forgotten.',
      durability: 72,
      verdict: 'Converts regulation into a barrier to entry — the most replicable moat archetype, executed best.',
    },
    {
      rank: 14,
      name: 'Kensho (S&P Global)',
      job: 'Not an end-user product — the AI/ML infrastructure layer that makes S&P\'s proprietary data machine-consumable and LLM-addressable.',
      pricing: 'No published rate card; usage- and scope-based. Acquired by S&P Global for ~$550M (2018). Value capture is internal — it defends the core data subscription franchise.',
      pricingConfidence: 'none',
      scale: 'S&P Global Market Intelligence reorganized in Jul 2026 into two verticals, one of them "Kensho Data & Platforms" — Kensho moved to the front of the business.',
      surfaces: 'APIs first — LLM-ready API with REST, a Python client that generates editable code, and an MCP server. Embedded in Capital IQ Pro as ChatIQ and Document Intelligence. S&P Global Marketplace.',
      moat: 'ENTITY RESOLUTION AS CHOKEPOINT. NERD and Link resolve messy third-party data to S&P company IDs — the output is only useful inside S&P\'s identifier space. Joins are forever; that is a data-gravity engine.',
      moatArchetype: 'semantic-lock-in',
      weakness: 'Value-capture ambiguity — acquired for $550M in 2018 and only now reorganized into the client-facing layer, arguably admitting the standalone-AI-product thesis did not monetize directly. TAM capped to S&P customers by construction.',
      lesson: 'Split retrieval into DETERMINISTIC and ADAPTIVE, and expose that boundary to the customer as a product surface, not an implementation detail. Structured facts return as JSON from a governed dataset; the model only does language.',
      durability: 85,
      verdict: 'The cleanest architectural idea in the whole study — and the one most directly applicable to our provenance stack.',
    },
    {
      rank: 15,
      name: 'PitchBook (Morningstar)',
      job: 'Private capital markets system-of-record — deal sourcing, comps, fund benchmarking, LP/GP research, diligence.',
      pricing: 'Per-licensed-user seats, quote-gated. Median observed contract $31,875/yr, range $20K–$122K. FY2025 segment revenue $671.8M, +8.6%.',
      pricingConfidence: 'confirmed',
      scale: '~10,200 client accounts, 113,451 licensed users. 1,800+ researchers; ~6M companies covered.',
      surfaces: 'Web platform, Chrome extension, Excel plugin, PowerPoint plug-in, Salesforce CRM plugin, mobile, Direct Data APIs, MCP connector into ChatGPT, integrations with Hebbia and Rogo.',
      moat: 'Citational authority — PitchBook numbers are the ones quoted in press and IC memos. Plus workflow lock-in: models and CRM records are built on PitchBook IDs, so ripping it out breaks live spreadsheets.',
      moatArchetype: 'licensed-data',
      weakness: 'THE DAMNING NUMBER: renewal rate fell 108% → 103% while licensed users stayed flat and revenue grew 8.6% — growth is price escalation on a static base. Corporate segment explicitly churning. Complaints cluster on stale data and cancellation friction.',
      lesson: 'Seat pricing on a flat user base turns renewal into an extortion negotiation. When your usage metric stops growing, price rises stop reading as value and start reading as a tax.',
      durability: 76,
      verdict: 'Citational authority is a real moat — but it is being monetized in a way that is visibly eroding retention.',
    },
    {
      rank: 16,
      name: 'Similarweb',
      job: 'Digital traffic intelligence — competitive benchmarking, market sizing, SEO/PPC and audience analysis, plus alt-data for investors.',
      pricing: 'Quote-only since 2026 (a transparency regression). Median observed contract $37,800/yr, range $14K–$96K. FY2025 revenue $282.6M, +13%.',
      pricingConfidence: 'confirmed',
      scale: '6,128 customers; 454 at ≥$100K ARR (63% of ARR). Market cap ~$640M, down ~57% YoY.',
      surfaces: 'Modular web platform, Chrome extension (dual-purpose: funnel AND panel data source), API/data feeds, MCP server, AI agents (Prospecting, Outreach, Amazon Keyword).',
      moat: 'Contributory panel + multi-source fusion — first-party analytics, a contributors network across millions of devices, public extraction, and ISP partnerships. Modeling is the moat, not collection: anyone can scrape, almost nobody can calibrate a panel into comparable metrics across 100M sites.',
      moatArchetype: 'licensed-data',
      weakness: 'THE NUMBER THAT MATTERS: net retention fell 101% → 98%, and the $100K+ cohort fell 112% → 103%. Expansion has stopped even at the top. Multi-year contracts rose 49% → 60% — buying retention with term length rather than earning it. Accuracy is a permanent structural complaint (estimates, not server logs).',
      lesson: 'Sell the ruler for the new world before your old ruler stops being read — Similarweb\'s Gen-AI Brand Visibility measures the very shift from clicks to LLM answers that erodes its core asset.',
      durability: 64,
      verdict: 'Instrumenting its own disruption is the right move; the 98% NRR says it may be too late.',
    },
    {
      rank: 17,
      name: 'Crunchbase',
      job: 'Company/funding discovery at the self-serve long tail — startup lookup, list building, light prospecting. Repositioned in 2025 as a predictions engine.',
      pricing: 'The only genuine PLG player here — Starter ~$29/user/mo, Pro $49–99, Business ~$199/mo, Enterprise $50K+. Median contract $20,000/yr with the highest negotiated discount (21.4%) of its peer set — i.e. the weakest pricing power.',
      pricingConfidence: 'estimate',
      scale: '4.3M+ organizations, 80M active users (company-reported). $107M raised; last round 2022.',
      surfaces: 'Web app, Chrome extension, API (free tier eliminated 2025), CRM integrations, Crunchbase News, and the public company profile pages themselves as an enormous organic-search footprint.',
      moat: 'SEO + entity-namespace ubiquity — "crunchbase.com/organization/x" is the default public URL for a startup, making it a de facto canonical company ID. Plus usage signals from 80M users: who is LOOKING at a company is a leading indicator rivals with 113K users cannot replicate.',
      moatArchetype: 'licensed-data',
      weakness: 'Outdated/incorrect data is the #1 recurring complaint — fatal for the prospecting use case it sells into. Killing the free API burned developer goodwill and spawned a whole genre of "Crunchbase alternatives" content.',
      lesson: 'Do not sell prophecy on top of a dataset people already think is stale. Credibility is sequential — you must be trusted on the observable before anyone buys your forecast.',
      durability: 58,
      verdict: 'Strong namespace, weak trust. The predictive pivot bets on the future while the base complaint is about the past.',
    },
    {
      rank: 18,
      name: 'Meltwater / Cision',
      job: 'Media monitoring, social listening, PR measurement, journalist database, press-release distribution. Same ingest→filter→alert→report machine, aimed at Comms.',
      pricing: 'Meltwater median $25,800/yr, range $5.4K–$57K. Hidden costs: onboarding $2K–$10K, overage charges, 3–7% annual renewal increases.',
      pricingConfidence: 'estimate',
      scale: 'Meltwater taken private ~$550M on ~$462M revenue — ~1.2x revenue, the market\'s verdict on commodity monitoring. Cision acquired for $2.74B, now ~$2.5B leveraged and downgraded to Caa1.',
      surfaces: 'Web dashboards, email digests, mobile, Slack/Teams alerting, API, Chrome extensions, Boolean query builders, PR Newswire distribution.',
      moat: 'Weak and eroding — licensed content, historical archives, saved Boolean searches, the journalist contact database. In practice the operative moat became CONTRACTUAL: 60-day auto-renewal clauses that "rarely appear on the contract you sign but live in the referenced terms of service".',
      moatArchetype: 'licensed-data',
      weakness: 'The most damning complaint set in the study — and it is about the CONTRACT, not the product. Auto-renewal traps, cancellation obstruction, aggressive sales. 4.1/5 across ~2,900 reviews: the product is fine, the company is the complaint.',
      lesson: 'When the product moat dies, companies reach for the contract moat — and it destroys the brand faster than competition would have. This is the terminal state of an alerting business that never converted monitoring into judgment.',
      durability: 30,
      verdict: 'The end state to avoid. Every one of those reviews is a permanent, indexed liability.',
    },
    {
      rank: 19,
      name: 'Flashpoint',
      job: 'Deep/dark web and closed-community risk intelligence — fraud, physical security, vulnerability intelligence, actor tracking.',
      pricing: 'Median observed contract $57,855/yr, range $54K–$80K — a notably tight band implying standardized packaging.',
      pricingConfidence: 'estimate',
      scale: '~$100M ARR exiting 2023, 800+ customers, 42% three-year CAGR, EBITDA-positive.',
      surfaces: 'Flashpoint Ignite unified workspace, API, SIEM/SOAR/TIP integrations, geospatial map UI inherited from Echosec.',
      moat: 'Operator access to closed illicit communities — requires persona maintenance and OPSEC, so it cannot be scraped or bought quickly. Acquired Echosec (2022) for geospatial OSINT, which unlocked the physical-security buyer on the same collection stack.',
      moatArchetype: 'deployability',
      weakness: 'Coverage claims are unverifiable by the buyer — you cannot audit access to a forum you cannot enter. Squeezed between Recorded Future breadth and Intel 471 depth. Uneven UX across acquired modules.',
      lesson: 'Buy the adjacent SENSOR, not the adjacent feature. Acquisitions that add a sensing modality compound; acquisitions that add a screen do not.',
      durability: 70,
      verdict: 'Quietly the healthiest economics in the threat cluster — profitable, growing, defensible collection.',
    },
    {
      rank: 20,
      name: 'Koyfin',
      job: 'Bloomberg-grade charting, screening and financial history at a consumer price — for retail, RIAs and small funds.',
      pricing: 'PUBLISHED, a rarity here: Free / Plus $39/mo / Premium $79/mo / Advisor Core $209/mo / Advisor Pro $299/mo ($3,588/yr). ~400x cheaper than a Bloomberg seat.',
      pricingConfidence: 'confirmed',
      scale: 'Only ~$6.67M raised across 5 rounds, last in 2021; ~56 employees.',
      surfaces: 'Web workspace, mobile, custodian/PMS integrations, client reporting. NO API and NO Excel/Sheets plugin — a fatal gap for the modeler persona it courts.',
      moat: 'Essentially none but price and taste. Replicable by any well-funded entrant. The only real stickiness is the advisor tier, where Koyfin generates a deliverable the advisor hands to their own client.',
      moatArchetype: 'workflow-shape',
      weakness: 'Delayed data on some exchanges, no real-time bid/ask, no options, weak news, crypto is price-only. No API blocks systematic users entirely.',
      lesson: 'Serve the persona who RESELLS your output, not the one who consumes it. Pricing power comes from being upstream of someone else\'s client relationship.',
      durability: 40,
      verdict: 'Excellent product, published pricing, zero moat — a permanent price-taker.',
    },
    {
      rank: 21,
      name: 'Brightwave',
      job: 'Turn a firehose of filings, transcripts, sell-side research and news into an investment memo an asset manager can act on.',
      pricing: 'Not disclosed. $21M raised total ($6M seed + $15M Series A, Decibel + OMERS). No round announced since Oct 2024.',
      pricingConfidence: 'none',
      scale: 'Clients collectively manage >$120B AUM; 4x revenue growth in the four months between rounds (off an unstated base).',
      surfaces: 'Web workspace positioned as "an IDE for information" — a control plane for fleets of autonomous research agents. Thinnest surface area in the cohort; no Office plugin found.',
      moat: 'Thin on data, real on attribution architecture and knowledge graphs (CEO holds KG patents from LinkedIn PhD work; co-created Databricks Dolly).',
      moatArchetype: 'workflow-shape',
      weakness: 'Sub-scale — $21M against Rogo\'s $300M+ and AlphaSense\'s $1B+. No proprietary content. Single-surface in a market where Excel/PPT is proving to be the wedge.',
      lesson: 'SENTENCE-LEVEL attribution is the right granularity for professional trust — document-level "sources" are theater and paragraph-level is still too coarse to defend a number in a meeting. But trust is a feature, not a business: every competitor copies it in two quarters.',
      durability: 48,
      verdict: 'Owns the single best provenance primitive in the market and lacks the scale to defend it — the most acquirable company on the list.',
    },
    {
      rank: 22,
      name: 'ZeroFox',
      job: 'External cybersecurity — find AND take down impersonation accounts, phishing domains, leaked credentials and brand abuse. Remediation, not just detection.',
      pricing: 'FY2023 ARR $156.7M across 1,203 subscription customers (147 above $100K ARR) — ~$130K average, but the median is far lower.',
      pricingConfidence: 'confirmed',
      scale: 'Taken private by Haveli at ~$350M enterprise value (Feb 2024, $1.14/share) — roughly 2.2x ARR, ~18 months after its SPAC-era listing.',
      surfaces: 'Web platform, API, SIEM/SOAR integrations, managed takedown service, dark web monitoring.',
      moat: 'Takedown execution — established legal process and relationships with registrars, hosts, app stores and platforms. Operational, not data.',
      moatArchetype: 'deployability',
      weakness: 'GAAP gross margin of 31% — a services business wearing a SaaS costume, which is exactly why it exited at 2.2x ARR.',
      lesson: 'Sell the OUTCOME (it makes false positives the vendor\'s problem — correct incentive alignment) but watch the unit economics of delivering it. Automate the remediation or price it as services; do not split the difference.',
      durability: 44,
      verdict: 'Right incentive model, wrong cost structure. The public market repudiated it in 18 months.',
    },
    {
      rank: 23,
      name: 'Sentieo (absorbed)',
      job: 'Was: the financial research workspace — document search, Notebook, Table Explorer — beloved by buy-side analysts.',
      pricing: 'N/A. Acquired by AlphaSense May 2022, price undisclosed. Customers auto-migrated by 31 Jan 2024; brand retired.',
      pricingConfidence: 'none',
      scale: 'Brought 1,000+ customers including 800+ institutional investment firms. Was first to successfully aggregate and redistribute GLG expert transcripts.',
      surfaces: 'Web workspace, Document Search, Notebook, Table Explorer, custom dashboards — all of which survived INSIDE AlphaSense.',
      moat: 'It had a PRODUCT moat (superior workflow UX) and no CONTENT moat — so it became the acquisition target rather than the acquirer.',
      moatArchetype: 'workflow-shape',
      weakness: 'Sub-scale against a competitor buying content. Lost the content arms race outright: AlphaSense could copy the UX, Sentieo could not copy the corpus.',
      lesson: 'A BETTER WORKFLOW LOSES TO A BIGGER CORPUS. Great UX gets you acquired; scarce data gets you the acquirer\'s seat. Feature velocity buys time to acquire distribution or content — it is not the endgame.',
      durability: 15,
      verdict: 'Dead, and the market\'s clearest verdict on product-vs-data. Kept in the catalog deliberately as the cautionary specimen.',
    },
  ] as EnterpriseSpecimen[],

  /** Where the market is unserved — and whether our estate can actually serve it. */
  unserved: [
    {
      gap: 'Provenance is PRESENTED, not PROVEN — the largest gap in the market',
      evidence: 'Every vendor now ships "citations", and every implementation is the same: a link back to a chunk. NOT ONE ships a verifiable evidence artifact — no cryptographic binding at capture, no hash-sealed chain from source → extraction → transformation → claim, no reproducibility guarantee. If a regulator or opposing counsel asks "prove this figure came from that filing at that timestamp and nothing altered it in between", no vendor can produce a machine-verifiable answer. Meanwhile EU AI Act Article 12 obligations went live Aug 2026 and procurement now gates on hash-chained audit trails.',
      ourPosition: 'This is precisely the Epoch E13 thesis already in the estate — bind-at-capture, fail-closed, CaptureReceipt as keystone — plus tritrpc proof_envelope + attestation_verifier, atlas/semantics (SHACL), prophet-truth and the model-governance-ledger. The gap between "here is a link" and "here is a receipt" is the whole opportunity, and it is the thing we were already building.',
      weCanServe: 'yes',
    },
    {
      gap: 'Governed AI output has no REFUSAL CONTRACT — every agent fails open',
      evidence: 'Between 2025-26 every incumbent bolted on an agent (SuperAnalyst, Felix, Navigator, ChatCBI, Intel Agents, Q Agents, Glean agents, AIP Agent Studio, Ask AI). NOT ONE publishes what its agent does when evidence is insufficient. No confidence-gated abstention, no "unsupported by retrieved evidence", no fail-closed behaviour. The cost is visible: a law firm filed fabricated citations in an Apr 2026 bankruptcy case; one audit of 45 citations in an AI-generated professional report found only FIVE pointed to real sources.',
      ourPosition: 'Fail-closed is our default posture, not a feature — autonomy_gate, promotion_controller, policy-fabric, the counter-test gate, and descend-abstain in fibered retrieval. We can ship an abstention contract nobody else offers.',
      weCanServe: 'yes',
    },
    {
      gap: 'No provenance FEDERATES across vendors',
      evidence: 'An analyst building one memo touches AlphaSense, PitchBook, internal SharePoint and a frontier model — four provenance regimes, four audit logs, zero interoperability. There is no portable evidence format and no cross-vendor chain of custody, so the memo\'s provenance is unverifiable in aggregate even when each component is individually cited.',
      ourPosition: 'A portable, signed evidence envelope is exactly what tritrpc proof_envelope and our metadata/forensic schema are shaped for. This is an open standard-shaped opening, not just a product one.',
      weCanServe: 'yes',
    },
    {
      gap: 'A canyon in the price curve between $1K and $20K/yr',
      evidence: 'Koyfin tops out at $3,588/yr and Perplexity Enterprise Pro is $400/seat — then the market jumps straight to AlphaSense $10-20K/seat, PitchBook ~$32K median, CB Insights ~$47K, Recorded Future ~$70K, Intel 471 $240K. The entire mid-market — corporate strategy, boutique advisors, mid-size funds, in-house counsel, policy shops — is priced out of governed intelligence and left with ungoverned ChatGPT. Simultaneously the largest unserved segment AND the largest uncontrolled-AI risk surface in professional work.',
      ourPosition: 'We are pre-revenue, so we can price INTO the canyon deliberately rather than defend a legacy seat model. Our cost base (on-device carry profiles, sovereign registry, owned infra) is compatible with that price point in a way a licensed-content incumbent\'s is not.',
      weCanServe: 'yes',
    },
    {
      gap: 'Sovereignty is served only at the government edge',
      evidence: 'Palantir (Apollo, IL6, air-gapped) and Primer (customer-hosted, DDIL) serve defense. On the commercial side sovereignty is essentially unavailable — AlphaSense offers an EU data-RESIDENCY region, which does not defeat the US CLOUD Act. Against that: sovereign cloud reached ~$80B in 2026 (+35.6%), ~20% of European firms are repatriating business-critical data, and the EDPB named on-premise inference the strongest available LLM data-protection mitigation.',
      ourPosition: 'SourceOS, SociOS-Linux, sovereign registry, Porter, on-device llama3.2 carry profiles and sealed tritrpc transport. Nobody sells a genuinely sovereign, self-hostable professional intelligence stack to a bank, law firm or pharma company. We could.',
      weCanServe: 'yes',
    },
    {
      gap: 'Estimates and observations are indistinguishable at field level',
      evidence: 'Similarweb models traffic (2-3x overstatement below 5K visits/mo). Crunchbase predicts fundraising at a self-reported "95% precision". PitchBook ships ML Valuation Estimates. NONE tag estimate-vs-observation in a machine-readable way per field — so a modelled number and a filed number enter the same downstream deck wearing identical clothes.',
      ourPosition: 'Our epistemic kernel and Truth = Law × Evidence contract are built to carry exactly this distinction as typed state rather than prose. Directly serviceable.',
      weCanServe: 'yes',
    },
    {
      gap: 'Entity resolution is a black box nobody can contest',
      evidence: 'Kensho Link/NERD, PitchBook methodology, Similarweb modelling — all unexplained and unappealable. When the system decides two records are the same company, the analyst cannot see the decision, the confidence, or dispute it. Recorded Future\'s top structural complaint is exactly this.',
      ourPosition: 'hellgraph + ontogenesis + the identity/entity-resolution plane could expose contestable ER with confidence and lineage. Real, but we have not built the contest UX — honest status: partial.',
      weCanServe: 'partly',
    },
    {
      gap: 'Nobody competes on EXIT',
      evidence: 'Data portability, contract exit terms and evidence export are pure differentiators no vendor claims — because every incumbent business model depends on their absence. PitchBook\'s free trial is described as misleading; Meltwater\'s auto-renewal as a trap.',
      ourPosition: '"You can leave, and take your provenance with you" is an unclaimed, genuinely disruptive position that costs us nothing to offer and is expensive for every incumbent to match.',
      weCanServe: 'yes',
    },
    {
      gap: 'A live permissions graph across enterprise SaaS',
      evidence: 'Glean\'s multi-year per-connector ACL mirroring with real-time delta-sync is the hardest thing to copy in the market and is why it is deployable company-wide.',
      ourPosition: 'We do NOT have this. No per-connector ACL ingestion, no delta-sync. A genuine, expensive gap.',
      weCanServe: 'no',
    },
    {
      gap: 'Licensed real-time data firehose',
      evidence: 'Bloomberg, AlphaSense ($930M for Tegus), Quid (2PB) and Perplexity Finance all rest on licensing we would have to buy. Intel 471\'s HUMINT inside closed criminal forums is un-scrapeable by construction.',
      ourPosition: 'We hold no comparable licences. Buy, partner, or compete on a different axis entirely — the evidence says the different axis is the better bet.',
      weCanServe: 'no',
    },
    {
      gap: 'Precision — nobody solved noise, they only distributed its cost',
      evidence: 'Recorded Future pushes tuning onto the customer; Dataminr onto human account managers; ZeroFox onto its own 31% gross margin; Intel 471 onto humans priced at $240K/yr. Dataminr\'s noise WORSENS in high-event-density regions — it degrades exactly when needed most.',
      ourPosition: 'A genuine opening but not a free one — it needs measured precision we do not yet publish. Honest status: unproven.',
      weCanServe: 'partly',
    },
  ] as UnservedGap[],

  ourRead:
    'THE ONE LESSON THAT GENERALIZES: in consumer software the loop is ENGAGEMENT; in professional intelligence the loop is EVIDENCE. Retention here is not habit — it is the accumulated, auditable, defensible record of work the customer cannot reconstruct anywhere else. Every incumbent built that record as a SIDE EFFECT of storing data. Nobody has yet built it as THE PRODUCT. That is the opening, and it is the one our estate was already pointed at. Concretely: two durable moat archetypes are already ours — DEPLOYABILITY (SourceOS, sovereign registry, on-device carry profiles, sealed tritrpc transport) and GOVERNED PROVENANCE (atlas/semantics, proof_envelope, attestation_verifier, model-governance-ledger, and the Epoch E13 bind-at-capture/CaptureReceipt line of work). Two are not: a live ACL PERMISSIONS GRAPH and LICENSED DATA — and the evidence says do not fight there. The defensible position nobody occupies is fail-closed, provenance-verifiable intelligence that runs where the customer decides, priced into the $1K-$20K canyon, exporting its evidence chain on the way out. Feedly is closest architecturally and lacks capital and a sovereignty story; Brightwave is closest on attribution granularity and lacks everything else; Palantir is closest on governance and deployment and is unavailable to anyone without seven figures and eighteen months. Meanwhile the incumbents have entered the HARVEST PHASE — seats falling while revenue rises, NRR decaying, valuations resetting — which is exactly the condition that invites displacement.',
  sourcing:
    'Palantir pricing is CONFIRMED from the public UK G-Cloud 14 price sheet — unusually hard numbers. Perplexity pricing is published. Glean, Hebbia and Quid publish no rate card; those seat prices are third-party estimates and flagged as such. Primer pricing is unavailable. Revenue/ARR figures are company-reported or third-party estimates. Hebbia\'s $13M ARR is a stale Jun-2024 disclosure with no 2026 update found.',
};
