<script setup lang="ts">
// Delivery Dashboard — sprint + board dynamics for the governed estate.
// The snapshot is GENERATED from merged-PR and issue evidence and regenerated by
// CI on merge to master, so the board cannot drift from what actually shipped.
// Per registry/board-spec.yaml, GitHub Projects is a render target, not the truth.
import { computed } from 'vue';
import SurfaceHeader from '../components/SurfaceHeader.vue';
import BoundaryNotice from '../components/BoundaryNotice.vue';
import { deliverySnapshot as snap } from '../data/deliverySnapshot';
import {
  overallGate, isUnverified, completionRate, scopeChurn, breachesWip,
  type FlowMetric,
} from '../features/delivery/contract';
import {
  backward, current, forward, loop, lanePriorities, pricingTiers, costModel,
  COMMIT_PERCENTILE,
} from '../features/delivery/horizons';
import { moscowLabel } from '../features/delivery/economics';

const gate = computed(() => overallGate(snap));
const isLive = computed(() => snap.sourceMode === 'live');
const completion = computed(() => completionRate(snap.sprint));
const churn = computed(() => scopeChurn(snap.sprint));
const maxCol = computed(() => Math.max(1, ...snap.columns.map((c) => c.count)));

function delta(m: FlowMetric): number | null {
  if (typeof m.previous !== 'number') return null;
  return m.value - m.previous;
}
function deltaTone(m: FlowMetric): string {
  const d = delta(m);
  if (d === null || d === 0) return 'is-flat';
  const improving = m.better === 'up' ? d > 0 : d < 0;
  return improving ? 'is-good' : 'is-bad';
}
function fmt(m: FlowMetric): string {
  if (m.unit === 'percent') return `${m.value}%`;
  if (m.unit === 'days') return `${m.value}d`;
  return String(m.value);
}
const shortCommit = computed(() => snap.commit.slice(0, 7));

// three horizons over one evidence base, plus the loop
const back = computed(() => backward(snap));
const now = computed(() => current(snap));
const fwd = computed(() => forward(snap));
const learn = computed(() => loop());
const maxWeek = computed(() => Math.max(1, ...snap.history.map((h) => h.merged)));
const rankedLanes = computed(() => [...lanePriorities].sort((a, b) => (b.wsjf ?? 0) - (a.wsjf ?? 0)));
const money = (n: number) => `$${n.toLocaleString()}`;
</script>

<template>
  <section class="dd" aria-labelledby="dd-title">
    <SurfaceHeader title="Delivery Dashboard" eyebrow="Governed estate · sprint & board dynamics">
      <template #badge>
        <span class="dd-badge" :class="isLive ? 'is-live' : 'is-fixture'">{{ snap.sourceMode }}</span>
        <span class="dd-badge dd-badge--gate" :class="`g-${gate.status}`">{{ gate.status }}</span>
      </template>
    </SurfaceHeader>

    <p id="dd-title" class="dd-lede">
      Sprint and board dynamics for <span class="dd-mono">{{ snap.repo }}</span>, computed from merged-PR and issue
      evidence — not read from a Projects board. Regenerated by CI on every merge to master, so what you see here
      is what actually shipped.
    </p>

    <BoundaryNotice
      :label="isLive ? 'live · computed from merge evidence' : 'fixture · not live evidence'"
      :tone="isLive ? 'muted' : 'warning'"
      :message="snap.boundaryNotice"
      aria-label="Delivery snapshot boundary"
    />

    <!-- RECEIPT -->
    <div class="dd-receipt">
      <span class="dd-receipt-k">Receipt</span>
      <span>commit <b class="dd-mono">{{ shortCommit }}</b></span>
      <span>generated <b>{{ new Date(snap.generatedAt).toLocaleString() }}</b></span>
      <span v-if="snap.workflowRun">
        run <a class="dd-link" :href="snap.workflowRun" target="_blank" rel="noopener">CI</a>
      </span>
      <span v-else class="dd-warn">no CI run — generated locally</span>
    </div>

    <!-- GATE -->
    <section class="dd-gate" :class="`g-${gate.status}`" aria-label="Delivery gate">
      <div class="dd-gate-h">
        <h2>{{ gate.name }}</h2>
        <span class="dd-gate-v">{{ gate.status }}</span>
      </div>
      <p>{{ gate.detail }}</p>
      <ul class="dd-gate-list">
        <li v-for="g in snap.gates" :key="g.name" :class="`g-${g.status}`">
          <span class="dd-gate-pill" :class="`g-${g.status}`">{{ g.status }}</span>
          <b>{{ g.name }}</b> — {{ g.detail }}
        </li>
      </ul>
    </section>

    <!-- SPRINT -->
    <section class="dd-block" aria-label="Sprint">
      <div class="dd-h">
        <h2>{{ snap.sprint.name }}</h2>
        <p>Commitment is a <b>declared</b> field; completion and carry-over are measured from merge evidence.</p>
      </div>
      <div class="dd-sprint">
        <div class="dd-burn">
          <div class="dd-burn-h">
            <span>Completion vs commitment</span>
            <b class="dd-mono">{{ completion }}%</b>
          </div>
          <div class="dd-burn-bar" aria-hidden="true">
            <span class="done" :style="{ width: `${Math.min(100, completion)}%` }" />
          </div>
          <div class="dd-burn-legend">
            <span><b>{{ snap.sprint.completed }}</b> completed</span>
            <span><b>{{ snap.sprint.committed }}</b> committed</span>
            <span><b>{{ snap.sprint.carriedOver }}</b> carried over</span>
            <span :class="churn > 25 ? 'dd-warn' : ''"><b>{{ churn }}%</b> scope churn</span>
          </div>
        </div>
      </div>
    </section>

    <!-- FLOW METRICS -->
    <section class="dd-block" aria-label="Flow metrics">
      <div class="dd-h">
        <h2>Flow metrics</h2>
        <p>Every metric declares its basis. A value asserted without evidence is marked <b>unverified</b> and cannot drive a decision.</p>
      </div>
      <div class="dd-metrics">
        <article v-for="m in snap.metrics" :key="m.id" class="dd-metric" :class="{ 'is-unverified': isUnverified(m) }">
          <div class="dd-metric-top">
            <span class="dd-metric-label">{{ m.label }}</span>
            <span class="dd-basis" :class="`b-${m.basis}`">{{ m.basis }}</span>
          </div>
          <div class="dd-metric-v">
            <b>{{ fmt(m) }}</b>
            <span v-if="delta(m) !== null" class="dd-delta" :class="deltaTone(m)">
              {{ delta(m)! > 0 ? '+' : '' }}{{ delta(m) }}
            </span>
          </div>
          <p class="dd-metric-note">{{ m.note }}</p>
          <p v-if="isUnverified(m)" class="dd-metric-ev dd-warn">⚠ no evidence ref — unverified</p>
          <p v-else class="dd-metric-ev dd-mono">{{ m.evidence }}</p>
        </article>
      </div>
    </section>

    <!-- ===================== BACKWARD ===================== -->
    <section class="dd-block" aria-label="Backward — what happened">
      <div class="dd-h">
        <h2><span class="dd-hz">Backward</span> What actually happened</h2>
        <p>{{ back.weeks }} weeks of measured history. {{ back.detail }}</p>
      </div>
      <div class="dd-hist">
        <div v-for="h in snap.history" :key="h.weekStart" class="dd-hist-col" :title="`${h.weekStart} → ${h.weekEnd}: ${h.merged} merged`">
          <span class="dd-hist-bar" :style="{ height: `${(h.merged / maxWeek) * 100}%` }" />
          <span class="dd-hist-n">{{ h.merged }}</span>
        </div>
      </div>
      <div class="dd-facts">
        <span><b>{{ back.totalMerged.toLocaleString() }}</b> merged</span>
        <span><b>{{ back.medianWeekly }}</b> median/wk</span>
        <span><b>{{ back.worstWeek }}–{{ back.bestWeek }}</b> range</span>
        <span v-if="back.variabilityRatio" class="dd-warn"><b>{{ back.variabilityRatio }}×</b> variability</span>
        <span v-if="back.costPerItem">
          <b>${{ back.costPerItem }}</b> cost/item
          <span class="dd-basis b-declared">{{ back.costBasis }}</span>
        </span>
      </div>
    </section>

    <!-- ===================== CURRENT ===================== -->
    <section class="dd-block" aria-label="Current — what is true now">
      <div class="dd-h">
        <h2><span class="dd-hz">Current</span> What is true right now</h2>
        <p>Flow state, prioritization discipline, and whether the system is stable enough to reason about.</p>
      </div>
      <div class="dd-two">
        <article class="dd-panel" :class="now.littlesLaw.valid ? 'ok' : 'warn'">
          <h3>Little's Law</h3>
          <p class="dd-panel-v" v-if="now.littlesLaw.valid">
            implied cycle time <b>{{ now.littlesLaw.impliedCycleTimeDays }}d</b>
          </p>
          <p class="dd-panel-v" v-else><b>not applied</b></p>
          <p class="dd-panel-d">{{ now.littlesLaw.detail }}</p>
        </article>
        <article class="dd-panel" :class="now.moscowUnprioritized ? 'warn' : now.moscow?.ok ? 'ok' : 'bad'">
          <h3>MoSCoW discipline</h3>
          <p class="dd-panel-v" v-if="now.moscow">
            Must is <b>{{ Math.round(now.moscow.mustShare * 100) }}%</b> of committed
          </p>
          <p class="dd-panel-v" v-else><b>unprioritized</b></p>
          <p class="dd-panel-d">{{ now.moscow ? now.moscow.detail : now.detail }}</p>
          <div v-if="!now.moscowUnprioritized" class="dd-moscow">
            <span v-for="k in (['must','should','could','wont'] as const)" :key="k" class="dd-mos" :class="`m-${k}`">
              {{ moscowLabel[k] }} {{ snap.moscow[k] }}
            </span>
          </div>
        </article>
      </div>
    </section>

    <!-- ===================== FORWARD ===================== -->
    <section class="dd-block" aria-label="Forward — what is likely">
      <div class="dd-h">
        <h2><span class="dd-hz">Forward</span> What is likely</h2>
        <p>
          Monte Carlo over {{ fwd.forecast.samples }} observed weekly throughputs —
          <b>never a velocity average</b>. {{ fwd.detail }}
        </p>
      </div>
      <div v-if="fwd.forecast.sufficient" class="dd-fc">
        <div class="dd-fc-h">
          <span>{{ fwd.backlog.toLocaleString() }} open items · {{ fwd.forecast.trials.toLocaleString() }} trials</span>
          <b class="dd-mono">commit @p{{ COMMIT_PERCENTILE }}: {{ fwd.commitWeeks }} weeks</b>
        </div>
        <div class="dd-fc-rows">
          <div v-for="p in fwd.forecast.percentiles" :key="p.p" class="dd-fc-row" :class="{ 'is-commit': p.p === COMMIT_PERCENTILE }">
            <span class="dd-fc-p">p{{ p.p }}</span>
            <span class="dd-fc-bar"><span :style="{ width: `${(p.periods / Math.max(1, fwd.forecast.percentiles[fwd.forecast.percentiles.length-1].periods)) * 100}%` }" /></span>
            <b class="dd-fc-n">{{ p.periods }}w</b>
          </div>
        </div>
      </div>
      <p v-else class="dd-warn">{{ fwd.forecast.detail }}</p>

      <div class="dd-h dd-h--sub">
        <h3>Pricing &amp; break-even</h3>
        <p>
          Tiers priced into the <b>$1K–$20K canyon</b> the incumbents leave empty, metered on governed artifacts
          rather than seats. All money inputs are <b>declared</b>, not measured — a scenario, not a projection.
        </p>
      </div>
      <div class="dd-tablewrap">
        <table class="dd-table">
          <thead><tr><th>Tier</th><th class="n">Annual</th><th>Meter</th><th class="n">Break-even accts</th><th class="n">Margin @25</th><th>Basis</th></tr></thead>
          <tbody>
            <tr v-for="(t, i) in pricingTiers" :key="t.id">
              <td class="dd-strong">{{ t.name }}</td>
              <td class="n">{{ money(t.annual) }}</td>
              <td class="dd-dim">{{ t.meter }}</td>
              <td class="n"><b>{{ fwd.breakEven[t.id] ?? '—' }}</b></td>
              <td class="n">{{ fwd.margins[i].marginPct !== null ? fwd.margins[i].marginPct + '%' : '—' }}</td>
              <td><span class="dd-basis" :class="`b-${t.basis}`">{{ t.basis }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>
      <p class="dd-note">Cost base: <b>{{ money(costModel.costPerPeriod) }}</b>/week — {{ costModel.note }}</p>

      <div class="dd-h dd-h--sub">
        <h3>WSJF — what to build next</h3>
        <p>Cost of Delay ÷ Job Size. Ranks value-per-unit-time, which is the actual bridge from a board to a P&amp;L. Cost-of-delay weights are <b>declared</b> strategic inputs from the market studies.</p>
      </div>
      <div class="dd-wsjf">
        <article v-for="(l, i) in rankedLanes" :key="l.lane" class="dd-lane" :class="{ 'is-top': i === 0 }">
          <div class="dd-lane-h">
            <span class="dd-lane-rank">{{ i + 1 }}</span>
            <b>{{ l.lane }}</b>
            <span class="dd-lane-w">WSJF {{ l.wsjf ?? '—' }}<span class="dd-dim"> · size {{ l.size }}</span></span>
          </div>
          <p>{{ l.rationale }}</p>
        </article>
      </div>
    </section>

    <!-- ===================== LEARNING LOOP ===================== -->
    <section class="dd-block" aria-label="Learning loop">
      <div class="dd-h">
        <h2><span class="dd-hz">Loop</span> Was the last forecast right?</h2>
        <p>A forecasting system that is never scored is a horoscope. This compares what was forecast against what happened and names the systematic bias.</p>
      </div>
      <article class="dd-panel" :class="learn.calibration.bias === 'calibrated' ? 'ok' : learn.calibration.bias === 'unknown' ? 'warn' : 'bad'">
        <h3>Calibration — {{ learn.calibration.bias }}</h3>
        <p class="dd-panel-v" v-if="learn.calibration.hitRate !== null">
          hit rate <b>{{ Math.round(learn.calibration.hitRate * 100) }}%</b>
          vs expected <b>{{ Math.round((learn.calibration.expectedRate ?? 0) * 100) }}%</b>
          <span class="dd-dim"> over {{ learn.calibration.resolved }} resolved</span>
        </p>
        <p class="dd-panel-d">{{ learn.detail }}</p>
        <p class="dd-panel-rec"><span>Correction</span>{{ learn.calibration.recommendation }}</p>
      </article>
    </section>

    <!-- BOARD -->
    <section class="dd-block" aria-label="Board">
      <div class="dd-h">
        <h2>Board distribution</h2>
        <p>Columns derived from evidence. A column with a declared WIP limit turns red when it breaches.</p>
      </div>
      <div class="dd-cols">
        <article v-for="c in snap.columns" :key="c.name" class="dd-col" :class="{ 'is-breach': breachesWip(c) }">
          <div class="dd-col-h">
            <span>{{ c.name }}</span>
            <b class="dd-mono">{{ c.count }}<template v-if="c.wipLimit">/{{ c.wipLimit }}</template></b>
          </div>
          <div class="dd-col-bar" aria-hidden="true">
            <span :style="{ width: `${(c.count / maxCol) * 100}%` }" />
          </div>
          <p v-if="c.aging" class="dd-warn">{{ c.aging }} aging</p>
          <p v-else class="dd-dim">no aging items</p>
        </article>
      </div>
    </section>

    <!-- ITEMS -->
    <section class="dd-block" aria-label="Work in progress">
      <div class="dd-h">
        <h2>Work in progress</h2>
        <p>Open items with age and risk. Risk is derived from age, not asserted.</p>
      </div>
      <div v-if="snap.items.length" class="dd-tablewrap">
        <table class="dd-table">
          <thead><tr><th>Ref</th><th>Title</th><th>Status</th><th>Lane</th><th class="n">Age</th><th>Risk</th></tr></thead>
          <tbody>
            <tr v-for="i in snap.items" :key="i.ref" :class="{ 'is-blocked': i.blocked }">
              <td class="dd-mono">{{ i.ref }}</td>
              <td>{{ i.title }}</td>
              <td>{{ i.status }}</td>
              <td class="dd-mono">{{ i.lane }}</td>
              <td class="n">{{ i.ageDays }}d</td>
              <td><span class="dd-risk" :class="`r-${i.risk}`">{{ i.risk }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>
      <p v-else class="dd-empty">
        No open pull requests — the board is clear. Throughput of {{ snap.sprint.completed }} merges with zero
        carry-over is a healthy flow state, not missing data.
      </p>
    </section>

    <!-- BOARDS -->
    <section class="dd-block" aria-label="Boards">
      <div class="dd-h">
        <h2>Boards rolled up</h2>
        <p>From <span class="dd-mono">registry/board-spec.yaml</span> — the declarative source of truth. Projects renders it; it does not define it.</p>
      </div>
      <div class="dd-boards">
        <span v-for="b in snap.boards" :key="b" class="dd-board">{{ b }}</span>
      </div>
    </section>
  </section>
</template>

<style scoped>
.dd {
  height: 100%; min-height: 0; overflow-y: auto;
  padding: 1rem 1.25rem 2.5rem; background: var(--bg); color: var(--text);
  display: flex; flex-direction: column; gap: 1rem;
}
.dd-badge {
  font-size: 0.56rem; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700;
  border-radius: 4px; padding: 0.05rem 0.32rem;
}
.dd-badge.is-live { color: var(--up); background: rgba(75,191,115,0.14); }
.dd-badge.is-fixture { color: var(--amber); background: var(--amber-soft); }
.dd-badge--gate.g-pass { color: var(--up); background: rgba(75,191,115,0.14); }
.dd-badge--gate.g-fail { color: var(--down); background: rgba(240,101,106,0.14); }
.dd-badge--gate.g-unverified { color: var(--amber); background: var(--amber-soft); }

.dd-lede { margin: 0; max-width: 96ch; font-size: var(--fs-base); line-height: 1.55; color: var(--text-2); }
.dd-mono { font-family: var(--mono, ui-monospace), monospace; font-size: 0.92em; }
.dd-link { color: var(--accent); }
.dd-warn { color: var(--amber); }
.dd-dim { color: var(--text-3); }

.dd-receipt {
  display: flex; flex-wrap: wrap; gap: 0.9rem; align-items: baseline;
  border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface);
  padding: 0.5rem 0.8rem; font-size: var(--fs-xs); color: var(--text-3);
}
.dd-receipt-k { font-size: 0.54rem; text-transform: uppercase; letter-spacing: 0.08em; font-weight: 700; color: var(--text-3); }
.dd-receipt b { color: var(--text-2); }

.dd-gate {
  border: 1px solid var(--line); border-left: 2px solid var(--line-2);
  border-radius: var(--radius-sm); background: var(--surface); padding: 0.85rem 1rem;
}
.dd-gate.g-pass { border-left-color: var(--up); background: rgba(75,191,115,0.06); }
.dd-gate.g-fail { border-left-color: var(--down); background: rgba(240,101,106,0.07); }
.dd-gate.g-unverified { border-left-color: var(--amber); background: var(--amber-soft); }
.dd-gate-h { display: flex; align-items: baseline; justify-content: space-between; gap: 1rem; }
.dd-gate-h h2 { margin: 0; font-size: var(--fs-md); font-weight: 640; }
.dd-gate-v { font-size: 0.56rem; text-transform: uppercase; letter-spacing: 0.07em; font-weight: 700; }
.dd-gate.g-pass .dd-gate-v { color: var(--up); }
.dd-gate.g-fail .dd-gate-v { color: var(--down); }
.dd-gate.g-unverified .dd-gate-v { color: var(--amber); }
.dd-gate > p { margin: 0.3rem 0 0.6rem; font-size: var(--fs-sm); color: var(--text-2); }
.dd-gate-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.3rem; }
.dd-gate-list li { font-size: var(--fs-xs); color: var(--text-3); }
.dd-gate-list b { color: var(--text-2); }
.dd-gate-pill {
  display: inline-block; font-size: 0.5rem; text-transform: uppercase; letter-spacing: 0.05em;
  font-weight: 700; border-radius: 3px; padding: 0.04rem 0.3rem; margin-right: 0.4rem;
}
.dd-gate-pill.g-pass { color: var(--up); background: rgba(75,191,115,0.14); }
.dd-gate-pill.g-fail { color: var(--down); background: rgba(240,101,106,0.14); }
.dd-gate-pill.g-unverified { color: var(--amber); background: var(--amber-soft); }

h2 { margin: 0; font-size: var(--fs-lg); font-weight: 640; letter-spacing: -0.01em; }
.dd-block { display: flex; flex-direction: column; gap: 0.75rem; }
.dd-h { display: flex; flex-direction: column; gap: 0.2rem; border-top: 1px solid var(--line); padding-top: 0.9rem; }
.dd-h p { margin: 0; font-size: var(--fs-sm); color: var(--text-3); max-width: 96ch; line-height: 1.5; }
.dd-h b { color: var(--text-2); }

.dd-sprint { display: grid; gap: 0.8rem; }
.dd-burn { border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); padding: 0.8rem 0.9rem; }
.dd-burn-h { display: flex; justify-content: space-between; align-items: baseline; font-size: var(--fs-xs); color: var(--text-3); }
.dd-burn-h b { font-size: var(--fs-md); color: var(--accent); }
.dd-burn-bar { height: 0.5rem; border-radius: 999px; background: var(--line-2); overflow: hidden; margin: 0.45rem 0; }
.dd-burn-bar .done { display: block; height: 100%; background: var(--up); }
.dd-burn-legend { display: flex; flex-wrap: wrap; gap: 1rem; font-size: var(--fs-xs); color: var(--text-3); }
.dd-burn-legend b { color: var(--text); font-variant-numeric: tabular-nums; }

.dd-metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 0.7rem; }
.dd-metric { border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); padding: 0.7rem 0.8rem; }
.dd-metric.is-unverified { border-color: rgba(227,179,65,0.45); background: var(--amber-soft); }
.dd-metric-top { display: flex; justify-content: space-between; align-items: baseline; gap: 0.4rem; }
.dd-metric-label { font-size: var(--fs-xs); color: var(--text-2); }
.dd-basis { font-size: 0.5rem; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; border-radius: 3px; padding: 0.04rem 0.3rem; }
.b-measured { color: var(--up); background: rgba(75,191,115,0.14); }
.b-declared { color: var(--amber); background: var(--amber-soft); }
.b-estimated { color: var(--neutral); background: rgba(139,148,158,0.14); }
.dd-metric-v { display: flex; align-items: baseline; gap: 0.4rem; margin: 0.25rem 0; }
.dd-metric-v b { font-size: 1.6rem; font-weight: 700; font-variant-numeric: tabular-nums; }
.dd-delta { font-size: var(--fs-xs); font-variant-numeric: tabular-nums; }
.dd-delta.is-good { color: var(--up); } .dd-delta.is-bad { color: var(--down); } .dd-delta.is-flat { color: var(--text-3); }
.dd-metric-note { margin: 0; font-size: 0.6rem; color: var(--text-3); line-height: 1.4; }
.dd-metric-ev { margin: 0.35rem 0 0; font-size: 0.54rem; color: var(--text-3); overflow-wrap: anywhere; }

.dd-cols { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 0.7rem; }
.dd-col { border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); padding: 0.7rem 0.8rem; }
.dd-col.is-breach { border-color: var(--down); background: rgba(240,101,106,0.07); }
.dd-col-h { display: flex; justify-content: space-between; align-items: baseline; font-size: var(--fs-xs); color: var(--text-2); }
.dd-col-h b { font-size: var(--fs-md); }
.dd-col-bar { height: 0.3rem; border-radius: 999px; background: var(--line-2); overflow: hidden; margin: 0.4rem 0 0.3rem; }
.dd-col-bar span { display: block; height: 100%; background: var(--accent); }
.dd-col p { margin: 0; font-size: 0.58rem; }

.dd-tablewrap { overflow-x: auto; border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); }
.dd-table { width: 100%; border-collapse: collapse; min-width: 640px; font-size: var(--fs-xs); }
.dd-table th, .dd-table td { padding: 0.45rem 0.6rem; border-bottom: 1px solid var(--line); text-align: left; }
.dd-table tbody tr:last-child td { border-bottom: none; }
.dd-table th { font-size: 0.54rem; text-transform: uppercase; letter-spacing: 0.07em; font-weight: 700; color: var(--text-3); background: var(--surface-2); }
.dd-table th.n, .dd-table td.n { text-align: right; font-variant-numeric: tabular-nums; }
tr.is-blocked td { background: rgba(240,101,106,0.06); }
.dd-risk { font-size: 0.5rem; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; border-radius: 3px; padding: 0.04rem 0.3rem; }
.r-low { color: var(--up); background: rgba(75,191,115,0.14); }
.r-medium { color: var(--amber); background: var(--amber-soft); }
.r-high { color: var(--down); background: rgba(240,101,106,0.14); }
.dd-empty { margin: 0; font-size: var(--fs-sm); color: var(--text-3); line-height: 1.5; max-width: 90ch; }

.dd-hz {
  display: inline-block; font-size: 0.54rem; text-transform: uppercase; letter-spacing: 0.08em;
  font-weight: 700; color: var(--accent); background: var(--accent-soft);
  border-radius: 3px; padding: 0.08rem 0.36rem; margin-right: 0.5rem; vertical-align: middle;
}
.dd-h--sub { border-top: 0; padding-top: 0.6rem; }
.dd-h--sub h3 { margin: 0; font-size: var(--fs-base); font-weight: 640; }

.dd-hist { display: flex; align-items: flex-end; gap: 0.3rem; height: 110px; border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); padding: 0.6rem; }
.dd-hist-col { flex: 1; display: flex; flex-direction: column; justify-content: flex-end; align-items: center; gap: 0.2rem; height: 100%; }
.dd-hist-bar { display: block; width: 100%; background: var(--accent); border-radius: 2px 2px 0 0; min-height: 2px; }
.dd-hist-n { font-size: 0.5rem; color: var(--text-3); font-variant-numeric: tabular-nums; }

.dd-facts { display: flex; flex-wrap: wrap; gap: 1rem; font-size: var(--fs-xs); color: var(--text-3); }
.dd-facts b { color: var(--text); font-variant-numeric: tabular-nums; }

.dd-two { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 0.8rem; }
.dd-panel { border: 1px solid var(--line); border-left: 2px solid var(--line-2); border-radius: var(--radius-sm); background: var(--surface); padding: 0.8rem 0.9rem; }
.dd-panel.ok { border-left-color: var(--up); }
.dd-panel.warn { border-left-color: var(--amber); }
.dd-panel.bad { border-left-color: var(--down); }
.dd-panel h3 { margin: 0 0 0.3rem; font-size: var(--fs-base); font-weight: 640; }
.dd-panel-v { margin: 0 0 0.35rem; font-size: var(--fs-sm); color: var(--text-2); }
.dd-panel-v b { color: var(--text); font-size: var(--fs-md); }
.dd-panel-d { margin: 0; font-size: 0.62rem; color: var(--text-3); line-height: 1.5; }
.dd-panel-rec { margin: 0.5rem 0 0; padding-top: 0.5rem; border-top: 1px solid var(--line); font-size: 0.62rem; color: var(--text-2); }
.dd-panel-rec span { display: block; font-size: 0.52rem; text-transform: uppercase; letter-spacing: 0.07em; font-weight: 700; color: var(--accent); margin-bottom: 0.15rem; }

.dd-moscow { display: flex; flex-wrap: wrap; gap: 0.3rem; margin-top: 0.5rem; }
.dd-mos { font-size: 0.52rem; border-radius: 3px; padding: 0.04rem 0.32rem; font-weight: 700; }
.m-must { color: var(--down); background: rgba(240,101,106,0.14); }
.m-should { color: var(--amber); background: var(--amber-soft); }
.m-could { color: var(--info); background: var(--info-soft); }
.m-wont { color: var(--neutral); background: rgba(139,148,158,0.14); }

.dd-fc { border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); padding: 0.8rem 0.9rem; }
.dd-fc-h { display: flex; justify-content: space-between; align-items: baseline; font-size: var(--fs-xs); color: var(--text-3); margin-bottom: 0.5rem; }
.dd-fc-h b { color: var(--accent); }
.dd-fc-rows { display: flex; flex-direction: column; gap: 0.3rem; }
.dd-fc-row { display: grid; grid-template-columns: 2.2rem 1fr 2.6rem; align-items: center; gap: 0.5rem; }
.dd-fc-p { font-size: 0.6rem; color: var(--text-3); font-variant-numeric: tabular-nums; }
.dd-fc-bar { height: 0.45rem; border-radius: 999px; background: var(--line-2); overflow: hidden; }
.dd-fc-bar span { display: block; height: 100%; background: var(--info); }
.dd-fc-row.is-commit .dd-fc-bar span { background: var(--accent); }
.dd-fc-row.is-commit .dd-fc-n { color: var(--accent); }
.dd-fc-n { font-size: var(--fs-xs); font-variant-numeric: tabular-nums; text-align: right; }

.dd-wsjf { display: flex; flex-direction: column; gap: 0.5rem; }
.dd-lane { border: 1px solid var(--line); border-radius: var(--radius-sm); background: var(--surface); padding: 0.6rem 0.8rem; }
.dd-lane.is-top { border-color: var(--accent); background: var(--accent-soft); }
.dd-lane-h { display: flex; align-items: baseline; gap: 0.5rem; }
.dd-lane-rank { font-family: var(--mono, ui-monospace), monospace; font-size: 0.6rem; color: var(--accent); font-weight: 700; }
.dd-lane-h b { flex: 1; font-size: var(--fs-sm); }
.dd-lane-w { font-size: 0.6rem; color: var(--text-2); font-variant-numeric: tabular-nums; }
.dd-lane p { margin: 0.25rem 0 0; font-size: 0.62rem; color: var(--text-3); line-height: 1.45; }

.dd-note { margin: 0.4rem 0 0; font-size: 0.6rem; color: var(--text-3); line-height: 1.45; }
.dd-strong { font-weight: 640; color: var(--text); }

.dd-boards { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.dd-board {
  font-size: 0.6rem; border-radius: 999px; padding: 0.15rem 0.55rem;
  background: rgba(45,212,191,0.12); color: var(--teal);
}

@media (max-width: 720px) { .dd { padding: 0.85rem 0.9rem 2rem; } }
</style>
