<template>
  <section class="nlb-page" aria-labelledby="nlb-title">
    <header class="nlb-hero">
      <div>
        <p class="nlb-kicker">NLBoot · Evidence Dashboard · {{ state.sourceMode }}</p>
        <h1 id="nlb-title">{{ state.title }}</h1>
        <p class="nlb-lede">{{ state.lede }}</p>
      </div>
      <div class="nlb-badge" aria-label="Evidence record count">
        <span class="nlb-badge-count">{{ state.recordTypeCount }}</span>
        <span class="nlb-badge-label">record types</span>
      </div>
    </header>

    <BoundaryNotice :label="state.boundaryLabel" :message="state.boundaryNotice" />

    <RouteStatePanel
      state="mock"
      title="Fixture boot evidence"
      :message="`${state.planRecord.length} plan fields, ${state.artifactCache.length} artifact records, and ${state.preExecProof.length} pre-exec checks are loaded from fixture state. No boot command, EFI mutation, disk write, reboot, or hardware access is active.`"
    />

    <article class="nlb-card">
      <h2>Plan record</h2>
      <p class="nlb-desc">Declarative boot plan generated by NLBoot before execution begins.</p>
      <table class="nlb-table"><tbody><tr v-for="row in state.planRecord" :key="row.field"><td class="nlb-field">{{ row.field }}</td><td>{{ row.value }}</td></tr></tbody></table>
    </article>

    <article class="nlb-card">
      <h2>Artifact cache record</h2>
      <p class="nlb-desc">Content-addressed cache entries resolved during the plan phase.</p>
      <table class="nlb-table">
        <thead><tr><th>Artifact</th><th>Digest</th><th>Source</th><th>Status</th></tr></thead>
        <tbody>
          <tr v-for="artifact in state.artifactCache" :key="artifact.name">
            <td class="nlb-field">{{ artifact.name }}</td>
            <td class="nlb-mono">{{ artifact.digest }}</td>
            <td>{{ artifact.source }}</td>
            <td><ModeBadge :label="artifact.status" :tone="artifact.status === 'hit' ? 'success' : 'danger'" /></td>
          </tr>
        </tbody>
      </table>
    </article>

    <article class="nlb-card">
      <h2>Pre-exec proof</h2>
      <p class="nlb-desc">Attestation that preconditions were satisfied before execution was authorized.</p>
      <div class="nlb-grid nlb-grid--two">
        <div v-for="item in state.preExecProof" :key="item.check" class="nlb-check">
          <span :class="`nlb-dot nlb-dot--${item.result}`" aria-hidden="true" />
          <div><strong>{{ item.check }}</strong><p>{{ item.detail }}</p></div>
        </div>
      </div>
    </article>

    <section class="nlb-grid nlb-grid--two">
      <article class="nlb-card">
        <h2>Exec proof</h2>
        <p class="nlb-desc">Post-execution attestation capturing exit status, timing, and output digest.</p>
        <table class="nlb-table"><tbody><tr v-for="row in state.execProof" :key="row.field"><td class="nlb-field">{{ row.field }}</td><td>{{ row.value }}</td></tr></tbody></table>
      </article>

      <article class="nlb-card">
        <h2>Boot-entry record</h2>
        <p class="nlb-desc">EFI / boot-loader entry represented by this fixture-backed evidence record.</p>
        <table class="nlb-table"><tbody><tr v-for="row in state.bootEntry" :key="row.field"><td class="nlb-field">{{ row.field }}</td><td>{{ row.value }}</td></tr></tbody></table>
      </article>
    </section>

    <article class="nlb-card">
      <h2>Apple Silicon adapter record</h2>
      <p class="nlb-desc">Hardware capability report from the Apple Silicon boot adapter mock fixture.</p>
      <table class="nlb-table">
        <thead><tr><th>Capability</th><th>Detected</th><th>Note</th></tr></thead>
        <tbody>
          <tr v-for="cap in state.appleAdapter" :key="cap.capability">
            <td class="nlb-field">{{ cap.capability }}</td>
            <td><ModeBadge :label="cap.detected ? 'yes' : 'no'" :tone="cap.detected ? 'success' : 'danger'" /></td>
            <td>{{ cap.note }}</td>
          </tr>
        </tbody>
      </table>
    </article>
  </section>
</template>

<script setup lang="ts">
import BoundaryNotice from '../components/BoundaryNotice.vue';
import ModeBadge from '../components/ModeBadge.vue';
import RouteStatePanel from '../components/RouteStatePanel.vue';
import { nlbootEvidenceState as state } from '../features/nlboot-evidence/state';
</script>

<style scoped>
.nlb-page { display: flex; flex-direction: column; gap: 1rem; color: var(--text, #f4f4f4); }
.nlb-hero, .nlb-card { border: 1px solid rgba(255,255,255,.14); border-radius: 18px; background: rgba(20,24,31,.82); box-shadow: 0 18px 48px rgba(0,0,0,.22); }
.nlb-hero { display: flex; justify-content: space-between; gap: 2rem; padding: 1.5rem; }
.nlb-kicker { margin: 0 0 .4rem; color: var(--accent, #78a9ff); font-size: .78rem; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; }
h1, h2, p { margin-top: 0; }
h1 { margin-bottom: .7rem; font-size: clamp(2rem, 4vw, 3.4rem); line-height: 1; }
h2 { margin-bottom: .65rem; font-size: 1.15rem; }
.nlb-lede, .nlb-desc, .nlb-card p, .nlb-check p { color: rgba(255,255,255,.70); line-height: 1.55; }
.nlb-lede { max-width: 780px; margin-bottom: 0; }
.nlb-badge { min-width: 170px; align-self: stretch; display: grid; place-content: center; border-radius: 16px; background: linear-gradient(145deg, rgba(120,169,255,.22), rgba(36,161,72,.18)); text-align: center; }
.nlb-badge-count { display: block; font-size: 3.2rem; font-weight: 800; }
.nlb-badge-label { color: rgba(255,255,255,.72); font-size: .82rem; text-transform: uppercase; letter-spacing: .08em; }
.nlb-grid { display: grid; gap: 1rem; }
.nlb-grid--two { grid-template-columns: repeat(auto-fit, minmax(340px, 1fr)); }
.nlb-card { padding: 1rem; }
.nlb-table { width: 100%; border-collapse: collapse; }
.nlb-table th, .nlb-table td { padding: .65rem .5rem; border-bottom: 1px solid rgba(255,255,255,.1); text-align: left; vertical-align: top; }
.nlb-table th { color: rgba(255,255,255,.6); font-size: .76rem; text-transform: uppercase; letter-spacing: .05em; }
.nlb-field { font-weight: 700; }
.nlb-mono { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: .78rem; overflow-wrap: anywhere; }
.nlb-check { display: flex; gap: .75rem; }
.nlb-dot { flex: 0 0 .75rem; width: .75rem; height: .75rem; margin-top: .35rem; border-radius: 50%; }
.nlb-dot--pass { background: #42be65; }
.nlb-dot--fail { background: #fa4d56; }
.nlb-dot--warn { background: #f1c21b; }
@media (max-width: 760px) { .nlb-hero { flex-direction: column; } .nlb-badge { min-height: 140px; } }
</style>
