// Delivery dashboard contract — sprint + board dynamics for the governed estate.
//
// Design rule, inherited from the estate's board-spec: GitHub Projects are a
// RENDER TARGET, not the truth. This snapshot is computed from merge/issue
// evidence and is regenerated by CI on merge to main, so the dashboard cannot
// drift from what actually shipped.
//
// Every metric declares its BASIS. A metric with basis 'declared' and no
// evidence ref is UNVERIFIED and must not drive a decision — the surface marks
// it and the CI gate fails closed on a verified metric that lost its evidence.

/** Where a number came from. The distinction the whole estate turns on. */
export type MetricBasis =
  | 'measured'   // computed from merge/issue events — reproducible from the repo
  | 'declared'   // asserted by a human or a spec; needs an evidence ref
  | 'estimated'; // modelled; never presentable as observed

export type SourceMode = 'live' | 'fixture';

export type FlowMetric = {
  id: string;
  label: string;
  value: number;
  unit: 'count' | 'days' | 'percent' | 'ratio';
  basis: MetricBasis;
  /** Evidence pointer — a query, workflow run, or spec path. Required unless measured. */
  evidence: string;
  /** Direction that counts as improvement. */
  better: 'up' | 'down';
  /** Previous period value, for delta. */
  previous?: number;
  note: string;
};

export type BoardColumn = {
  name: string;
  count: number;
  /** Work-in-progress limit from board-spec, if declared. */
  wipLimit?: number;
  /** Items older than the aging threshold. */
  aging: number;
};

export type BoardItem = {
  ref: string;
  title: string;
  status: string;
  lane: string;
  /** Days in current status. */
  ageDays: number;
  risk: 'low' | 'medium' | 'high';
  /** Governance fields from the estate board-spec. */
  gate?: string;
  warrant?: string;
  blocked: boolean;
};

export type SprintState = {
  name: string;
  startedAt: string;
  endsAt: string;
  /** Committed at sprint start. */
  committed: number;
  completed: number;
  addedMidSprint: number;
  carriedOver: number;
};

export type CiGate = {
  name: string;
  /** pass = evidence present and within threshold. */
  status: 'pass' | 'fail' | 'unverified';
  detail: string;
};

export type DeliverySnapshot = {
  /** 'live' only when generated from real merge/issue evidence. */
  sourceMode: SourceMode;
  generatedAt: string;
  /** Commit the snapshot was computed at — the receipt. */
  commit: string;
  /** CI run that produced it, when generated in CI. */
  workflowRun: string | null;
  repo: string;
  boundaryNotice: string;
  sprint: SprintState;
  metrics: FlowMetric[];
  columns: BoardColumn[];
  items: BoardItem[];
  gates: CiGate[];
  /** Boards this rolls up, from registry/board-spec.yaml. */
  boards: string[];
};

// ---------------------------------------------------------------------------

/** A metric is unverified when it asserts something without evidence. */
export function isUnverified(m: FlowMetric): boolean {
  return m.basis !== 'measured' && m.evidence.trim() === '';
}

/** Sprint completion against commitment, guarded against a zero commitment. */
export function completionRate(s: SprintState): number {
  if (s.committed <= 0) return 0;
  return Math.round((s.completed / s.committed) * 100);
}

/** Scope churn — added mid-sprint as a share of commitment. */
export function scopeChurn(s: SprintState): number {
  if (s.committed <= 0) return 0;
  return Math.round((s.addedMidSprint / s.committed) * 100);
}

/** A column breaches when it has a declared WIP limit and exceeds it. */
export function breachesWip(c: BoardColumn): boolean {
  return typeof c.wipLimit === 'number' && c.count > c.wipLimit;
}

/**
 * The overall gate. Fails closed: any failing CI gate, any unverified metric,
 * or a fixture snapshot in a context that requires live evidence.
 */
export function overallGate(s: DeliverySnapshot): CiGate {
  const failing = s.gates.filter((g) => g.status === 'fail');
  if (failing.length) {
    return { name: 'Delivery gate', status: 'fail', detail: `${failing.length} gate(s) failing: ${failing.map((g) => g.name).join(', ')}.` };
  }
  const unverified = s.metrics.filter(isUnverified);
  if (unverified.length) {
    return { name: 'Delivery gate', status: 'unverified', detail: `${unverified.length} metric(s) assert a value with no evidence ref.` };
  }
  if (s.sourceMode === 'fixture') {
    return { name: 'Delivery gate', status: 'unverified', detail: 'Snapshot is fixture-backed — not computed from merge evidence.' };
  }
  return { name: 'Delivery gate', status: 'pass', detail: `Computed from merge evidence at ${s.commit.slice(0, 7)}.` };
}
