export type RouteMaturity = 'L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5';
export type RouteStateMode = 'design' | 'fixture' | 'mock-adapter' | 'live-fallback' | 'live-only' | 'taxonomy';
export type NavTier = 'top' | 'left-rail' | 'tab-only' | 'hidden';

export type RouteRegistryEntry = {
  path: string;
  label: string;
  domain: string;
  maturity: RouteMaturity;
  stateMode: RouteStateMode;
  navTier: NavTier;
  userJob: string;
  ownerPlane: string;
  boundary: string;
  primaryObject: string;
  breadcrumbs: string[];
  railLabel?: string;
  tabs?: Array<{ label: string; to: string }>;
};

export const routeRegistry: RouteRegistryEntry[] = [
  {
    path: '/news',
    label: 'News',
    domain: 'News & Events',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Triage news across feeds — Feedly-style source rail + card stream + reader.',
    ownerPlane: 'client-vue NewsFeed (fixture); future live intake = feed-intelligence lane',
    boundary: 'Fixture-backed reader conforming to FeedSource/FeedItem contracts; no live feed/membrane/memory adapter active.',
    primaryObject: 'feed reader',
    breadcrumbs: ['News & Events', 'Feed'],
    railLabel: '☷',
  },
  {
    path: '/markets/indices-funds',
    label: 'Market Monitor',
    domain: 'Capital & Markets',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Monitor indices, a watchlist, and instrument detail with sparklines.',
    ownerPlane: 'client-vue MarketMonitor (fixture, deterministic series); future live quote adapter',
    boundary: 'Fixture-backed monitor with deterministic series; no live quote/market-data adapter active.',
    primaryObject: 'market monitor',
    breadcrumbs: ['Capital & Markets', 'Market Monitor'],
    railLabel: '☶',
  },
  {
    path: '/economy/macro-economics',
    label: 'Macro & Sectors',
    domain: 'Economy & Industry',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Read the macro KPI board and sector breadth/momentum with signals.',
    ownerPlane: 'client-vue EconomySectorBoard (fixture); future macro-data adapter',
    boundary: 'Fixture-backed KPI + sector board with deterministic series; no live macro-data adapter active.',
    primaryObject: 'sector board',
    breadcrumbs: ['Economy & Industry', 'Macro & Sectors'],
    railLabel: '☴',
  },
  {
    path: '/people/search',
    label: 'Directory',
    domain: 'People & Society',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Search entities; view a profile, ego-graph, OSINT footprint (social accounts, selectors, sources), and identity-resolution confidence.',
    ownerPlane: 'client-vue PeopleDirectory (fixture); future identity/entity-resolution + scope-governed OSINT collection lane',
    boundary: 'Fixture-backed directory + OSINT stub over open sources; masked selectors withheld by collection scope. No live identity graph or collector active.',
    primaryObject: 'entity directory',
    breadcrumbs: ['People & Society', 'Directory'],
    railLabel: '☵',
  },
  {
    path: '/people/social-networks',
    label: 'Social Signals',
    domain: 'People & Society',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Watch a live-style social signal stream across tracked entities, trends, and sentiment.',
    ownerPlane: 'client-vue SocialSignals (fixture); future scope-governed social-collection lane',
    boundary: 'Fixture-backed social board over open sources; no live collector/streaming API active.',
    primaryObject: 'social signal board',
    breadcrumbs: ['People & Society', 'Social Signals'],
    railLabel: '☰',
  },
  {
    path: '/law/international-law',
    label: 'Docket',
    domain: 'Law & Regulation',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Track rules/bills/cases on a docket and read the redline of what changed.',
    ownerPlane: 'client-vue LawDocket (fixture); future legal-intake lane',
    boundary: 'Fixture-backed docket + redline with a provenance ribbon; no live legal-data adapter active.',
    primaryObject: 'legal docket',
    breadcrumbs: ['Law & Regulation', 'Docket'],
    railLabel: '☳',
  },
  {
    path: '/noetica',
    label: 'Noetica',
    domain: 'Noetica',
    maturity: 'L4',
    stateMode: 'live-fallback',
    navTier: 'top',
    userJob: 'Converse with the agent (social surface) — streamed answers with a live reasoning trace.',
    ownerPlane: 'Noetica agent-machine /api/chat (agentic loop + Noetica SSE events)',
    boundary: 'Streams the live agentic loop; degrades to an honest error when no model/keys are configured.',
    primaryObject: 'chat surface',
    breadcrumbs: ['Noetica', 'Chat'],
    railLabel: '◇',
    tabs: [
      { label: 'Chat', to: '/noetica' },
      { label: 'Reasoning Chain', to: '/noetica/reasoning-chain' },
    ],
  },
  {
    path: '/noetica/reasoning-chain',
    label: 'Reasoning Chain Inspector',
    domain: 'Noetica',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'tab-only',
    userJob: 'Inspect a conversation chain in four stages — Annotation → Concepts → Variants → Execution — with annotations bound to the governed semantic-role KIND vocabulary and candidate plans ranked by the governed variant scorer.',
    ownerPlane: 'client-vue ReasoningChainInspector (seed fixtures); KINDs from regis-entity-graph#22; authorship into the KE/dictionary workbench contract',
    boundary: 'Fixture-backed over three seed conversation chains; no live conversation-chain binding and no durable KE writeback yet — authorship events are held in an unsigned in-memory ledger.',
    primaryObject: 'reasoning chain',
    breadcrumbs: ['Noetica', 'Reasoning Chain Inspector'],
    tabs: [
      { label: 'Chat', to: '/noetica' },
      { label: 'Reasoning Chain', to: '/noetica/reasoning-chain' },
    ],
  },
  {
    path: '/weather/forecast',
    label: 'Weather & Resources',
    domain: 'Weather & Natural Resources',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Monitor regional conditions, a 7-day forecast timeline, and active weather/resource alerts.',
    ownerPlane: 'client-vue WeatherMonitor (fixture, deterministic); future weather/hazard data adapter',
    boundary: 'Fixture-backed conditions + timeline + alerts; no live weather/hazard feed active. Map exploration lives in Maps.',
    primaryObject: 'weather monitor',
    breadcrumbs: ['Weather & Natural Resources', 'Weather & Forecast'],
    railLabel: '☲',
  },
  {
    path: '/map',
    label: 'Maps',
    domain: 'Maps & Analytics',
    maturity: 'L4',
    stateMode: 'live-fallback',
    navTier: 'top',
    userJob: 'Review GAIA/OpenStreetMap world-model evidence and fallback posture.',
    ownerPlane: 'Prophet Platform OSM Map API + client-vue shell',
    boundary: 'Live API or deterministic demo fallback; no production tile serving or safety-critical navigation.',
    primaryObject: 'map workbench',
    breadcrumbs: ['Maps & Analytics', 'OpenStreetMap', 'GAIA world model'],
    railLabel: '⌖',
    tabs: [{ label: 'Map Workbench', to: '/map' }],
  },
  {
    path: '/weather/natural-resources',
    label: 'Land & Resources',
    domain: 'Weather & Natural Resources',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Layer 0 of the economy — land, minerals, water, energy, forests, fisheries with reserves, renewability, and tenure; each links up the value chain (extraction → commodity → market) and out to the graph / map / twin.',
    ownerPlane: 'client-vue LandResources (fixture endowments carry HellGraph refs + geo + twin handles); live land-registry / GAIA / economic-prophet adapters resolve the same identities',
    boundary: 'Fixture resource endowments; outbound links target the supply chain, markets, /knowledge/graph, /map, and the twin. No live registry yet.',
    primaryObject: 'resource endowments',
    breadcrumbs: ['Weather & Natural Resources', 'Land & Resources'],
  },
  {
    path: '/analytics/supply-chain',
    label: 'Supply Chain',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Trace a commodity supply chain (mine→smelter→port→route→buyer) as a cross-domain graph; each node links out to the knowledge graph, the map, the digital twin, and related markets/economy/weather/news.',
    ownerPlane: 'client-vue SupplyChainMap (fixture nodes carry HellGraph refs + geo + twin handles); live graph/GAIA/economic-prophet adapters resolve the same identities',
    boundary: 'Fixture supply-chain graph; outbound links target /knowledge/graph, /map, and the twin surface. No live graph or geo resolution yet.',
    primaryObject: 'supply-chain graph',
    breadcrumbs: ['Maps & Analytics', 'Supply Chain'],
  },
  {
    path: '/analytics/twin-workshop',
    label: 'Twin Workshop',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'live-fallback',
    navTier: 'top',
    userJob: 'See and build twins — submit a GenesisSeed → a verified Twin through the created→authorized→verified lifecycle, each transition emitting a replayable TwinEventEnvelope; fail-closed on an invalid seed.',
    ownerPlane: 'client-vue TwinOperatingPicture over cloudTwinApi; live = cloud-twin service on prophet-platform (GET/POST /twins, GET /twins/{id}/events), fixture = client-side lifecycle simulation',
    boundary: 'Live registry when VITE_CLOUD_TWIN_API_BASE is wired to cloud-twin; otherwise a fixture registry with client-side simulated builds. Seeds validate fail-closed (422) in both modes.',
    primaryObject: 'twin',
    breadcrumbs: ['Maps & Analytics', 'Twin Workshop'],
  },
  {
    path: '/analytics/model-tournament',
    label: 'Model Tournament',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'live-fallback',
    navTier: 'top',
    userJob: 'Run the provider-neutral model tournament → iSOTA: three corpora (provider seed, Sherlock workload, adversarial/edge), a fail-closed Stage 0→4 pipeline, and a Sherlock-weighted leaderboard scored across 10 axes. Promotion is decided only by scores on our corpora, never by which provider ships eval tooling.',
    ownerPlane: 'client-vue ModelTournament (fixture-first; illustrative seed scores exercise the harness mechanism). Live seam = dashboard-bff GET /v1/intelligence-superiority; a future /v1/model-tournament producer replaces the fixture via VITE_ISOTA_API_BASE.',
    boundary: 'Illustrative seed scores — the harness MECHANISM, not a measured benchmark result; providers are neutral labels. Governance-gated models are rejected at Stage 0 (fail-closed). No live tournament producer wired yet.',
    primaryObject: 'model tournament',
    breadcrumbs: ['Maps & Analytics', 'Model Tournament'],
  },
  {
    path: '/analytics/twin-world-model',
    label: 'Twin World Model',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'live-fallback',
    navTier: 'top',
    userJob: 'See twins as geospatially-grounded state-space world models — located on a common operating picture over a GAIA risk field, wired into an ontology (Twin→Region→Sensor→Feed→Event→Policy→Hologram), and driven by a governed impulse core x⁺ = A·x + B·(G·u) where a closed gate holds the twin fail-closed.',
    ownerPlane: 'client-vue TwinWorldModel over cloudTwinApi (Twin registry, live-fallback) + a self-contained equirectangular COP and a pure-TS state-space engine; live twins = cloud-twin on prophet-platform, GAIA risk field = advisory demo overlay',
    boundary: 'Live twin registry when VITE_CLOUD_TWIN_API_BASE is wired; otherwise a fixture registry. The geospatial picture and GAIA risk field are advisory in-browser renders — not production tile serving or safety-critical navigation. Closed impulse gates reject fail-closed.',
    primaryObject: 'twin world model',
    breadcrumbs: ['Maps & Analytics', 'Twin World Model'],
  },
  {
    path: '/analytics/trending-infographics',
    label: 'Trending Infographics',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Headline infographics — top trending topic, biggest market move, best-retained cohort, dominant sentiment.',
    ownerPlane: 'client-vue AnalyticsStudio (charts platform fixtures); future live analytics adapter',
    boundary: 'Derived from the platform fixtures; no fabricated series, no live analytics pipeline.',
    primaryObject: 'analytics studio',
    breadcrumbs: ['Maps & Analytics', 'Trending Infographics'],
  },
  {
    path: '/analytics/charts-graphs',
    label: 'Charts & Graphs',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Chart gallery over the platform data — bar, area, and donut charts across markets, economy, social, and behavioral datasets.',
    ownerPlane: 'client-vue AnalyticsStudio (charts platform fixtures); future live analytics adapter',
    boundary: 'Read-only charts over typed fixtures; no live analytics pipeline.',
    primaryObject: 'analytics studio',
    breadcrumbs: ['Maps & Analytics', 'Charts & Graphs'],
  },
  {
    path: '/analytics',
    label: 'Custom Analytics',
    domain: 'Maps & Analytics',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Pick a dataset and see its chart — a lightweight metric explorer over the platform data.',
    ownerPlane: 'client-vue AnalyticsStudio (charts platform fixtures); future live analytics adapter',
    boundary: 'Read-only charts over typed fixtures; no live analytics pipeline.',
    primaryObject: 'analytics studio',
    breadcrumbs: ['Maps & Analytics', 'Custom Analytics'],
  },
  {
    path: '/professional-intelligence/competitive/enterprise',
    label: 'Enterprise Intelligence',
    domain: 'Professional Intelligence',
    maturity: 'L1',
    stateMode: 'fixture',
    navTier: 'tab-only',
    userJob: 'Read market 2 — professional & market intelligence platforms, their moats ranked by durability, where the market is unserved, and which axis we can actually win on.',
    ownerPlane: 'client-vue competitive-intelligence fixture (research digest)',
    boundary: 'Fixture-backed research digest; pricing confidence is declared per specimen (Palantir and Perplexity confirmed, most others third-party estimates).',
    primaryObject: 'enterprise market teardown',
    breadcrumbs: ['Professional Intelligence OS', 'Competitive Intelligence', 'Enterprise Intelligence'],
    tabs: [
      { label: 'Operating Dashboard', to: '/professional-intelligence' },
      { label: 'Competitive Intelligence', to: '/professional-intelligence/competitive' },
      { label: 'Market Portfolio', to: '/professional-intelligence/competitive/markets' },
      { label: 'Enterprise Intelligence', to: '/professional-intelligence/competitive/enterprise' },
      { label: 'Feature Library', to: '/professional-intelligence/competitive/features' },
      { label: 'Gates', to: '/gates' },
      { label: 'Policies', to: '/policies' },
    ],
  },
  {
    path: '/professional-intelligence/competitive/markets',
    label: 'Market Portfolio',
    domain: 'Professional Intelligence',
    maturity: 'L1',
    stateMode: 'fixture',
    navTier: 'tab-only',
    userJob: 'See every market the estate competes in and how much competitive intelligence coverage each actually has — including the ones with none.',
    ownerPlane: 'client-vue competitive-intelligence fixture; coverage is a declared register',
    boundary: 'Declared coverage register, not a measurement. Uncovered markets have no teardown data behind them and carry no assessment.',
    primaryObject: 'market coverage register',
    breadcrumbs: ['Professional Intelligence OS', 'Competitive Intelligence', 'Market Portfolio'],
    tabs: [
      { label: 'Operating Dashboard', to: '/professional-intelligence' },
      { label: 'Competitive Intelligence', to: '/professional-intelligence/competitive' },
      { label: 'Market Portfolio', to: '/professional-intelligence/competitive/markets' },
      { label: 'Enterprise Intelligence', to: '/professional-intelligence/competitive/enterprise' },
      { label: 'Feature Library', to: '/professional-intelligence/competitive/features' },
      { label: 'Gates', to: '/gates' },
      { label: 'Policies', to: '/policies' },
      { label: 'Runs', to: '/runs' },
      { label: 'Attestations', to: '/attestations' },
    ],
  },
  {
    path: '/professional-intelligence/competitive/features',
    label: 'Feature Library',
    domain: 'Professional Intelligence',
    maturity: 'L1',
    stateMode: 'fixture',
    navTier: 'tab-only',
    userJob: 'Read the feature galaxy — every feature across the specimens, normalized to canonical types and aligned to real tritfabric modules and foundation models, through six typed lenses.',
    ownerPlane: 'client-vue competitive-intelligence fixture; capability owners grounded in tritfabric/tritrpc/model registries',
    boundary: 'Fixture-backed alignment digest; demand is labelled evidence or hypothesis per row and readiness is our assessment, not live telemetry.',
    primaryObject: 'feature-type alignment',
    breadcrumbs: ['Professional Intelligence OS', 'Competitive Intelligence', 'Feature Library'],
    tabs: [
      { label: 'Operating Dashboard', to: '/professional-intelligence' },
      { label: 'Competitive Intelligence', to: '/professional-intelligence/competitive' },
      { label: 'Market Portfolio', to: '/professional-intelligence/competitive/markets' },
      { label: 'Enterprise Intelligence', to: '/professional-intelligence/competitive/enterprise' },
      { label: 'Feature Library', to: '/professional-intelligence/competitive/features' },
      { label: 'Gates', to: '/gates' },
      { label: 'Policies', to: '/policies' },
      { label: 'Runs', to: '/runs' },
      { label: 'Attestations', to: '/attestations' },
    ],
  },
  {
    path: '/professional-intelligence/competitive',
    label: 'Competitive Intelligence',
    domain: 'Professional Intelligence',
    maturity: 'L1',
    stateMode: 'fixture',
    navTier: 'tab-only',
    userJob: 'Read the One-Trick Playbook — a ranked teardown of single-feature consumer apps, the shared money machine, and how each trick maps onto our estate.',
    ownerPlane: 'client-vue competitive-intelligence fixture (research digest); future live source = competitive-intel lane',
    boundary: 'Fixture-backed research digest; figures are third-party estimates, not live telemetry or runtime authority.',
    primaryObject: 'competitive teardown ranking',
    breadcrumbs: ['Professional Intelligence OS', 'Competitive Intelligence'],
    tabs: [
      { label: 'Operating Dashboard', to: '/professional-intelligence' },
      { label: 'Competitive Intelligence', to: '/professional-intelligence/competitive' },
      { label: 'Market Portfolio', to: '/professional-intelligence/competitive/markets' },
      { label: 'Enterprise Intelligence', to: '/professional-intelligence/competitive/enterprise' },
      { label: 'Feature Library', to: '/professional-intelligence/competitive/features' },
      { label: 'Gates', to: '/gates' },
      { label: 'Policies', to: '/policies' },
      { label: 'Runs', to: '/runs' },
      { label: 'Attestations', to: '/attestations' },
    ],
  },
  {
    path: '/professional-intelligence',
    label: 'Professional Intelligence',
    domain: 'Professional Intelligence',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Review operating alignment, gates, controls, and replayed evidence posture.',
    ownerPlane: 'client-vue product-control fixture; future live source in Prophet Platform/DelEx',
    boundary: 'Fixture-backed evidence surface; no live telemetry or runtime authority.',
    primaryObject: 'operating dashboard state',
    breadcrumbs: ['Professional Intelligence OS', 'Operating dashboard'],
    railLabel: 'PI',
    tabs: [
      { label: 'Operating Dashboard', to: '/professional-intelligence' },
      { label: 'Competitive Intelligence', to: '/professional-intelligence/competitive' },
      { label: 'Market Portfolio', to: '/professional-intelligence/competitive/markets' },
      { label: 'Enterprise Intelligence', to: '/professional-intelligence/competitive/enterprise' },
      { label: 'Feature Library', to: '/professional-intelligence/competitive/features' },
      { label: 'Gates', to: '/gates' },
      { label: 'Policies', to: '/policies' },
      { label: 'Runs', to: '/runs' },
      { label: 'Attestations', to: '/attestations' },
    ],
  },
  {
    path: '/control-plane',
    label: 'SourceOS',
    domain: 'SourceOS Lifecycle',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'Review SourceOS ReleaseSet and BootReleaseSet lifecycle posture.',
    ownerPlane: 'client-vue evidence surface; contracts owned by SourceOS/NLBoot repos',
    boundary: 'Evidence-only; no enrollment, device assignment, disk write, reboot, or host mutation.',
    primaryObject: 'lifecycle evidence state',
    breadcrumbs: ['SourceOS Lifecycle', 'Control-plane evidence'],
    railLabel: 'CP',
    tabs: [
      { label: 'Lifecycle Control', to: '/control-plane' },
      { label: 'NLBoot Evidence', to: '/nlboot' },
      { label: 'Gates', to: '/gates' },
      { label: 'Attestations', to: '/attestations' },
    ],
  },
  {
    path: '/nlboot',
    label: 'NLBoot Evidence',
    domain: 'SourceOS Lifecycle',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Inspect NLBoot plan, artifact cache, proof, adapter, and boot-entry records.',
    ownerPlane: 'client-vue evidence surface; NLBoot owns executable contracts',
    boundary: 'Evidence-only; no boot commands, EFI mutation, disk writes, reboots, or hardware contact.',
    primaryObject: 'boot evidence records',
    breadcrumbs: ['SourceOS Lifecycle', 'NLBoot evidence'],
    railLabel: 'NB',
  },
  {
    path: '/reader',
    label: 'Reader',
    domain: 'Feed Intelligence',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Review feed-intelligence item normalization, membrane, memory, and graph intent.',
    ownerPlane: 'client-vue fixture; future contracts in BearBrowser, SlashTopics, New Hope, MemoryMesh, MeshRush',
    boundary: 'UI-first fixture; no live feed fetching, ActivityPub, MemoryMesh writeback, MeshRush traversal, or browser bridge.',
    primaryObject: 'canonical feed item',
    breadcrumbs: ['Feed Intelligence', 'Reader'],
    railLabel: '▤',
  },
  {
    path: '/journal',
    label: 'Adapter Seams',
    domain: 'Adapter Seams',
    maturity: 'L3',
    stateMode: 'mock-adapter',
    navTier: 'left-rail',
    userJob: 'Inspect fixture-backed journal event stream shape.',
    ownerPlane: 'client-vue mock TriRPC seam',
    boundary: 'Mock/test mode only; no live backend stream, authorization, or writeback.',
    primaryObject: 'journal event',
    breadcrumbs: ['Adapter Seams', 'Journal stream'],
    railLabel: 'J',
    tabs: [
      { label: 'Journal', to: '/journal' },
      { label: 'Code Search', to: '/code' },
      { label: 'Reader', to: '/reader' },
    ],
  },
  {
    path: '/code',
    label: 'Code Search',
    domain: 'Adapter Seams',
    maturity: 'L3',
    stateMode: 'mock-adapter',
    navTier: 'left-rail',
    userJob: 'Inspect fixture-backed code-search result shape.',
    ownerPlane: 'client-vue mock TriRPC seam',
    boundary: 'Mock/test mode only; no GitHub, Sourcegraph, credential access, or repository indexing.',
    primaryObject: 'code search result',
    breadcrumbs: ['Adapter Seams', 'Code search'],
    railLabel: 'CS',
  },
  {
    path: '/workbench',
    label: 'Operator Workbench',
    domain: 'Operator Workbench',
    maturity: 'L1',
    stateMode: 'design',
    navTier: 'top',
    userJob: 'Navigate the IBM-Carbon operator surfaces (Axonius asset graph, SCOPE-D, Orion, wargames) and the estate/cognitive-systems architecture maps.',
    ownerPlane: 'client-vue static render-harness (public/workbench); IBM-Carbon fidelity mirror, migrating to native components',
    boundary: 'Design render-harness mounted in an iframe; no live data or runtime authority.',
    primaryObject: 'operator surface',
    breadcrumbs: ['Operator Workbench', 'Surfaces'],
    railLabel: 'WB',
    tabs: [
      { label: 'Render-harness', to: '/workbench' },
      { label: 'SCOPE-D (native)', to: '/workbench/scope-d' },
    ],
  },
  {
    path: '/workbench/scope-d',
    label: 'SCOPE-D Fabric',
    domain: 'Operator Workbench',
    maturity: 'L1',
    stateMode: 'design',
    navTier: 'tab-only',
    userJob: 'Inspect the SCOPE-D collector-policy fabric (axiom chain A1–A7, E4/E5/E6 lanes, admissibility gate) as native Vue+Carbon components.',
    ownerPlane: 'client-vue native components (src/components/workbench); first screen of the render-harness → native migration',
    boundary: 'Design surface with static spec data; no live collector telemetry, PEP verdict resolution, or runtime authority.',
    primaryObject: 'collector-policy fabric',
    breadcrumbs: ['Operator Workbench', 'SCOPE-D'],
    railLabel: 'SD',
    tabs: [
      { label: 'Render-harness', to: '/workbench' },
      { label: 'SCOPE-D (native)', to: '/workbench/scope-d' },
    ],
  },
  {
    path: '/capability/algorithmic-trading',
    label: 'Algorithmic Trading',
    domain: 'Capabilities',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Monitor strategies — equity curves, Sharpe/drawdown/win-rate, live signals, and recent fills; risk-gated with order routing disabled.',
    ownerPlane: 'client-vue AlgoTradingBoard (fixture strategies); future strategy/backtest + execution adapter',
    boundary: 'Fixture-backed strategy board; no live broker, quote feed, or order routing. Single-ticker fills deep-link to the market monitor.',
    primaryObject: 'strategy board',
    breadcrumbs: ['Capabilities', 'Algorithmic Trading'],
    railLabel: 'AT',
  },
  {
    path: '/capability/nlp-information-extraction',
    label: 'NLP & Information Extraction',
    domain: 'Capabilities',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Extract entities, relations, claims, and sentiment from a document — highlighted spans with typed, confidence-scored output.',
    ownerPlane: 'client-vue NlpExtractionBench (fixture docs); future extractor via SynapseIQ / entity-resolution lane',
    boundary: 'Read-only extraction over fixture documents; no live NLP model, no PII writeback.',
    primaryObject: 'extraction bench',
    breadcrumbs: ['Capabilities', 'NLP & Information Extraction'],
    railLabel: 'IE',
  },
  {
    path: '/capability/experiments-simulations',
    label: 'Experiments & Simulations',
    domain: 'Capabilities',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Compare A/B arms, ablations, boards, and simulations — arm scores, uplift vs baseline, significance, and the run manifest.',
    ownerPlane: 'client-vue ExperimentsBoard (fixture runs); future live board runner + eval harness',
    boundary: 'Fixture board reflecting the evaluation shape; no live runner or model. Every arm carries seed/n provenance.',
    primaryObject: 'experiment board',
    breadcrumbs: ['Capabilities', 'Experiments & Simulations'],
    railLabel: 'XP',
  },
  {
    path: '/capability/behavioral-analytics',
    label: 'Behavioral Analytics',
    domain: 'Capabilities',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Read cohort behavior — conversion funnels, D7 retention, weekly-active trend, and top events per segment.',
    ownerPlane: 'client-vue BehavioralAnalytics (fixture cohorts); future product-analytics adapter',
    boundary: 'Aggregate-only cohort analytics; no per-user PII, no live event pipeline.',
    primaryObject: 'cohort analytics',
    breadcrumbs: ['Capabilities', 'Behavioral Analytics'],
    railLabel: 'BA',
  },
  {
    path: '/capability/mobile-app-development',
    label: 'Mobile & App Development',
    domain: 'Capabilities',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Track shippable apps — build pipelines, platform targets/channels, artifacts, and recent releases across BearBrowser/TurtleTerm/Noetica/SourceOS.',
    ownerPlane: 'client-vue AppBuildBoard (fixture builds); future CI/build adapter via Forge + cross-platform packaging',
    boundary: 'Fixture build board; no live CI, signing keys, or store publishing wired.',
    primaryObject: 'app build board',
    breadcrumbs: ['Capabilities', 'Mobile & App Development'],
    railLabel: 'MA',
  },
  {
    path: '/people/labor-market',
    label: 'Labor Market',
    domain: 'People & Society',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'top',
    userJob: 'The request-centric labor market — labor as request + response + evidence + fulfillment + trust. Structured requests (RFI/RFP/RFQ/role/collaboration/apprenticeship/review/availability), per-response fit (never a global human-worth score), awards + work ledgers, and trust events.',
    ownerPlane: 'client-vue LaborMarket (fixture mirrors the sourceos-spec LaborRequest/LaborResponse/FitScore/LaborAward/TrustEvent contract); requesters/responders reference the human-spine networks + People',
    boundary: 'Fixture-backed request market; compensation transparency mandatory; fit is request-scoped. No live matching or payment rail wired.',
    primaryObject: 'labor request',
    breadcrumbs: ['People & Society', 'Labor Market'],
  },
  {
    path: '/marketplace',
    label: 'Marketplace',
    domain: 'Operations',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'The governed-triparty marketplace — netting cells that clear trades by coupling value + proof + authority + disclosure; lifecycle, truth classes, admissibility lattice, and typed proof-carrying bundles. Cells clear supply-chain trades.',
    ownerPlane: 'client-vue Marketplace (fixture cells mirror the sourceos-spec NettingCell / TripartyBundle contract); a live NettingCell/PolicyKernel/ReserveManager runtime settles the same objects',
    boundary: 'Fixture-backed clearing surface; release/refund/export disposed by policy, not confidence. No live settlement rail (ASI/MPE) wired.',
    primaryObject: 'triparty netting cell',
    breadcrumbs: ['Operations', 'Marketplace'],
    railLabel: 'MP',
  },
  {
    path: '/agentic-os',
    label: 'Agentic Operating System',
    domain: 'Operations',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'The agentic OS over the stack — agent pods pursue objectives under a governed capture cadence, delta-control SLAs, shared libraries, and a 12-dimension readiness scorecard; objects anchor to real estate repos.',
    ownerPlane: 'client-vue AgenticOS (fixture drafts the sourceos-spec agentic-OS contract: Opportunity / AgentPod / ReadinessScore / CaptureCadence / DeltaControl / SharedLibrary)',
    boundary: 'Fixture-backed operating console; a live registry adapter resolves the same canonical objects. AgentPod fills the existing urn:srcos:agent-pod: reference in AgentMachineReceipt.',
    primaryObject: 'agentic operating system',
    breadcrumbs: ['Operations', 'Agentic Operating System'],
    railLabel: 'OS',
  },
  {
    path: '/capability/dashboard',
    label: 'User Dashboard',
    domain: 'Capabilities',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Operator home — one-glance tiles across every domain (markets, news, economy, people, law, weather, social, alerts) with deep-links and an Ask-Noetica line.',
    ownerPlane: 'client-vue OperatorDashboard (aggregates the domain fixtures); future live data via each domain adapter',
    boundary: 'Read-only fixture aggregation; every tile deep-links into the domain surface. No live data adapter active.',
    primaryObject: 'operator dashboard',
    breadcrumbs: ['Capabilities', 'User Dashboard'],
    railLabel: 'DB',
  },
  {
    path: '/research',
    label: 'Research Capture',
    domain: 'Operator Workbench',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Capture open working tabs into a durable research list on close — never lose research.',
    ownerPlane: 'client-vue capture store (localStorage first); future clip-inbox / capture-spine backend',
    boundary: 'Local, non-destructive capture; enrichment verbs (find-similar/entity-extraction) are pending adapters.',
    primaryObject: 'research capture list',
    breadcrumbs: ['Operator Workbench', 'Research Capture'],
    railLabel: 'RC',
  },
  // --- Agent Machine cockpit (live on-device surfaces via Noetica agent-machine /api/*) ---
  {
    path: '/workstation/pipelines',
    label: 'Pipelines',
    domain: 'Workstation',
    maturity: 'L4',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Review local GitOps — Argo CD application sync/health + CI toolchain.',
    ownerPlane: 'Noetica agent-machine /api/pipelines/status (Argo CD + toolchain probe)',
    boundary: 'Read-only status from the local cluster; honest "not configured" when Argo/kubectl absent.',
    primaryObject: 'Argo application list',
    breadcrumbs: ['Workstation', 'Pipelines'],
    railLabel: 'PL',
  },
  {
    path: '/workstation/deploy',
    label: 'Deploy',
    domain: 'Workstation',
    maturity: 'L4',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Check the control-plane readiness — continuum repo + runtime toolchain + cluster.',
    ownerPlane: 'Noetica agent-machine /api/deploy/status (sourceos-continuum + toolchain probe)',
    boundary: 'Read-only detection; does not mutate clusters. Notes surface what is missing.',
    primaryObject: 'deploy readiness report',
    breadcrumbs: ['Workstation', 'Deploy'],
    railLabel: 'DP',
  },
  {
    path: '/workstation/services',
    label: 'Services · DevSpaces',
    domain: 'Workstation',
    maturity: 'L4',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'View trust-namespace DevSpaces (Nocalhost BaseSpace/MeshSpace) and live status.',
    ownerPlane: 'Noetica agent-machine /api/devspace/list (kube namespaces + nhctl)',
    boundary: 'Read-only namespace/status view; no dev-mode switch executed from here yet.',
    primaryObject: 'DevSpace list',
    breadcrumbs: ['Workstation', 'Services'],
    railLabel: 'SV',
  },
  {
    path: '/workstation/terminal',
    label: 'Terminal',
    domain: 'Workstation',
    maturity: 'L3',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Run allow-listed operator CLIs (prophet · sourceosctl) on-device, injection-safe.',
    ownerPlane: 'Noetica agent-machine /api/terminal/{status,run} (allow-listed spawn, no shell)',
    boundary: 'Only allow-listed binaries/subcommands; no shell interpolation; streamed via SSE.',
    primaryObject: 'operator console',
    breadcrumbs: ['Workstation', 'Terminal'],
    railLabel: 'TM',
  },
  {
    path: '/knowledge/studio',
    label: 'Knowledge Studio',
    domain: 'Knowledge & Ontology',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Author a type system, dictionaries and rules; adjudicate ground truth; train, evaluate and promote an extraction model — with capture and licence provenance and a fail-closed promotion gate.',
    ownerPlane: 'client-vue knowledge-studio fixture; future live extractor = slate/nlp + SynapseIQ, gate = atlas/autopilot promotion_controller',
    boundary: 'Fixture-backed workspace. No extraction model executes, no document is ingested, and all metrics are illustrative fixtures rather than measured performance. Write actions are disabled — this surface has no ingestion or promotion authority.',
    primaryObject: 'extraction workspace',
    breadcrumbs: ['Knowledge & Ontology', 'Knowledge Studio'],
    railLabel: 'KS',
    tabs: [
      { label: 'Knowledge Studio', to: '/knowledge/studio' },
      { label: 'IE Bench', to: '/capability/nlp-information-extraction' },
      { label: 'Ontology', to: '/ontology' },
      { label: 'Knowledge Graph', to: '/knowledge/graph' },
    ],
  },
  {
    path: '/knowledge/graph',
    label: 'Knowledge Graph',
    domain: 'Knowledge & Data',
    maturity: 'L4',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Explore the live HellGraph subgraph — view-scoped, degree-ranked, re-rootable.',
    ownerPlane: 'Noetica agent-machine /api/graph/{surface,health} (HellGraph sidecar)',
    boundary: 'Read-only visualization of a bounded subgraph; empty when the graph is unpopulated.',
    primaryObject: 'knowledge subgraph',
    breadcrumbs: ['Knowledge & Data', 'Knowledge Graph'],
    railLabel: 'KG',
  },
  {
    path: '/data/search',
    label: 'Search',
    domain: 'Knowledge & Data',
    maturity: 'L3',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Search local (lampstand) vs platform (sherlock) side by side.',
    ownerPlane: 'Noetica agent-machine /api/search (lampstand + sherlock brokers)',
    boundary: 'Honest per-source "not configured / unreachable" state; no fabricated results.',
    primaryObject: 'search results',
    breadcrumbs: ['Knowledge & Data', 'Search'],
    railLabel: 'SR',
  },
  {
    path: '/ai/labs',
    label: 'Model Labs',
    domain: 'Models & Forge',
    maturity: 'L2',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Review the Apple-aligned model catalog — on-device base + per-lab LoRA adapters + server tier.',
    ownerPlane: 'Noetica agent-machine /api/labs/catalog (model-catalog)',
    boundary: 'Catalog + routing view; adapter/model activation not driven from here yet.',
    primaryObject: 'model catalog',
    breadcrumbs: ['Models & Forge', 'Model Labs'],
    railLabel: 'ML',
  },
  {
    path: '/forge/import',
    label: 'Add Local Repo',
    domain: 'Models & Forge',
    maturity: 'L3',
    stateMode: 'live-fallback',
    navTier: 'tab-only',
    userJob: 'Pull a local folder into the sovereign Gitea — create repo + git-push, nothing leaves the box.',
    ownerPlane: 'Noetica agent-machine /api/forge/{browse,import-local} (folder picker + SSE push)',
    boundary: 'Local filesystem browse + push to a configured Gitea; requires an endpoint + token.',
    primaryObject: 'local import flow',
    breadcrumbs: ['Models & Forge', 'Add Local Repo'],
    railLabel: 'FI',
  },
  {
    path: '/control-plane/executions',
    label: 'Executions Ledger',
    domain: 'Infrastructure',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Review governed agent executions — each row shows a verdict + receipt warrant, not a boolean, with capabilities held vs used on expand.',
    ownerPlane: 'client-vue ExecutionsLedger (fixture, demoLedger); contract = prophet-core-contracts execution-receipt; future live /svc/executions',
    boundary: 'Fixture-backed ledger conforming to the ExecutionReceipt contract; no live executions/membrane adapter active yet.',
    primaryObject: 'execution receipt',
    breadcrumbs: ['Infrastructure', 'Executions Ledger'],
    railLabel: '▤',
  },
  {
    path: '/control-plane/containment',
    label: 'Containment (blast-radius)',
    domain: 'Infrastructure',
    maturity: 'L2',
    stateMode: 'fixture',
    navTier: 'left-rail',
    userJob: 'Pick a foothold, see its reachable set, choose a sever scope (full/selective), and read the residual + contained delta before isolating.',
    ownerPlane: 'client-vue ContainmentGraph (fixture, demoTopology); engine = gbrg-core::containment (sociosphere); future live /svc/containment',
    boundary: 'Fixture-backed graph; residual computed client-side mirroring gbrg-core sever_residual; no live topology/EDR isolation adapter active yet.',
    primaryObject: 'containment reading',
    breadcrumbs: ['Infrastructure', 'Containment'],
    railLabel: '☣',
  },
];

export function routesForNavTier(tier: NavTier): RouteRegistryEntry[] {
  return routeRegistry.filter((route) => route.navTier === tier);
}

export function registryEntryForPath(path: string): RouteRegistryEntry | undefined {
  return routeRegistry.find((entry) => path === entry.path || path.startsWith(`${entry.path}/`));
}

export function entriesForDomain(domain: string): RouteRegistryEntry[] {
  return routeRegistry.filter((entry) => entry.domain === domain);
}

export function topNavRoutes(): RouteRegistryEntry[] {
  return routesForNavTier('top');
}

export function leftRailRoutes(): RouteRegistryEntry[] {
  return routeRegistry.filter((entry) => entry.navTier === 'top' || entry.navTier === 'left-rail');
}
