// GENERATED by scripts/generate-delivery-snapshot.mjs — do not edit by hand.
// Regenerated by CI on merge to master so the dashboard cannot drift from what shipped.
// sourceMode 'live' at commit c5941ad.
import type { DeliverySnapshot } from '../features/delivery/contract';

export const deliverySnapshot: DeliverySnapshot = {
  "sourceMode": "live",
  "generatedAt": "2026-08-03T21:31:31.721Z",
  "commit": "c5941adeb7a5d0eacf90ae74929c2808129c59c7",
  "workflowRun": "https://github.com/SocioProphet/socioprophet/actions/runs/30854927085",
  "repo": "SocioProphet + SourceOS-Linux",
  "windowDays": 14,
  "boundaryNotice": "Estate-wide rollup across SocioProphet and SourceOS-Linux over 14 days, computed from merged-PR and issue search evidence. Boards come from registry/board-spec.yaml — Projects is a render target, not the truth. Throughput history is bucketed weekly and resampled by Monte Carlo; no velocity average is used anywhere. Cost and price inputs are DECLARED, not measured, and every money figure inherits the weakest basis of its inputs.",
  "perOrg": [
    {
      "org": "SocioProphet",
      "merged": 952,
      "openPrs": 295,
      "closedIssues": 100,
      "openIssues": 716
    },
    {
      "org": "SourceOS-Linux",
      "merged": 170,
      "openPrs": 5,
      "closedIssues": 9,
      "openIssues": 24
    }
  ],
  "history": [
    {
      "weekStart": "2026-05-25",
      "weekEnd": "2026-06-01",
      "merged": 305
    },
    {
      "weekStart": "2026-06-01",
      "weekEnd": "2026-06-08",
      "merged": 107
    },
    {
      "weekStart": "2026-06-08",
      "weekEnd": "2026-06-15",
      "merged": 176
    },
    {
      "weekStart": "2026-06-15",
      "weekEnd": "2026-06-22",
      "merged": 194
    },
    {
      "weekStart": "2026-06-22",
      "weekEnd": "2026-06-29",
      "merged": 343
    },
    {
      "weekStart": "2026-06-29",
      "weekEnd": "2026-07-06",
      "merged": 419
    },
    {
      "weekStart": "2026-07-06",
      "weekEnd": "2026-07-13",
      "merged": 67
    },
    {
      "weekStart": "2026-07-13",
      "weekEnd": "2026-07-20",
      "merged": 432
    },
    {
      "weekStart": "2026-07-20",
      "weekEnd": "2026-07-27",
      "merged": 161
    },
    {
      "weekStart": "2026-07-27",
      "weekEnd": "2026-08-03",
      "merged": 966
    }
  ],
  "arrivals": 1211,
  "sprint": {
    "name": "Rolling 14-day window",
    "startedAt": "2026-07-20T21:31:31.721Z",
    "endsAt": "2026-08-03T21:31:31.721Z",
    "committed": 1422,
    "completed": 1122,
    "addedMidSprint": 0,
    "carriedOver": 300
  },
  "moscow": {
    "must": 0,
    "should": 0,
    "could": 0,
    "wont": 0,
    "labelsSeen": 0
  },
  "metrics": [
    {
      "id": "throughput",
      "label": "Throughput",
      "value": 1122,
      "unit": "count",
      "basis": "measured",
      "better": "up",
      "evidence": "search: org:{SocioProphet|SourceOS-Linux} is:pr is:merged merged:>=2026-07-20",
      "note": "PRs merged across the estate in 14 days."
    },
    {
      "id": "throughput-median-wk",
      "label": "Median weekly throughput",
      "value": 249.5,
      "unit": "count",
      "basis": "measured",
      "better": "up",
      "evidence": "median of 10 weekly buckets",
      "note": "Median, not mean — the distribution is heavily skewed."
    },
    {
      "id": "wip",
      "label": "Work in progress",
      "value": 300,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "search: is:pr is:open across 2 orgs",
      "note": "Open pull requests across the estate."
    },
    {
      "id": "aging",
      "label": "Aging WIP",
      "value": 25,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "open PRs older than 7d",
      "note": "Open PRs older than 7 days — the flow risk."
    },
    {
      "id": "issues-closed",
      "label": "Issues closed",
      "value": 109,
      "unit": "count",
      "basis": "measured",
      "better": "up",
      "evidence": "search: is:issue is:closed closed:>=2026-07-20",
      "note": "Issues closed in 14 days."
    },
    {
      "id": "issues-open",
      "label": "Open issues",
      "value": 740,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "search: is:issue is:open",
      "note": "Open issues across the estate — the forecastable backlog."
    },
    {
      "id": "arrivals",
      "label": "Arrivals",
      "value": 1211,
      "unit": "count",
      "basis": "measured",
      "better": "down",
      "evidence": "search: is:pr created:>=2026-07-20",
      "note": "PRs opened in 14 days — a flow, measured so Little's Law can be validated rather than assumed."
    }
  ],
  "columns": [
    {
      "name": "Backlog (open issues)",
      "count": 740,
      "aging": 0
    },
    {
      "name": "In review (open PRs)",
      "count": 300,
      "wipLimit": 40,
      "aging": 25
    },
    {
      "name": "Merged (14d)",
      "count": 1122,
      "aging": 0
    },
    {
      "name": "Closed (14d)",
      "count": 109,
      "aging": 0
    }
  ],
  "items": [
    {
      "ref": "gitpod#244",
      "title": "[intellij] Update IDE image to build version 252.26199.169",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 318,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "gitpod#245",
      "title": "[goland] Update IDE image to build version 252.26199.158",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 318,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "gitpod#246",
      "title": "[phpstorm] Update IDE image to build version 252.26199.163",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 315,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "gitpod#247",
      "title": "[pycharm] Update IDE image to build version 252.26199.168",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 314,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "gitpod#249",
      "title": "[goland] Update IDE image to build version 252.26830.102",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 304,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "gitpod#248",
      "title": "[intellij] Update IDE image to build version 252.26830.84",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 304,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "gitpod#251",
      "title": "[pycharm] Update IDE image to build version 252.26830.99",
      "status": "In review",
      "lane": "gitpod",
      "ageDays": 301,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "giantnetes-terraform#2",
      "title": "Bump giantswarm/install-binary-action from 1.1.0 to 4.1.0",
      "status": "In review",
      "lane": "giantnetes-terraform",
      "ageDays": 64,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "giantnetes-terraform#4",
      "title": "Bump actions/checkout from 3 to 7",
      "status": "In review",
      "lane": "giantnetes-terraform",
      "ageDays": 43,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "kustomize#5",
      "title": "Bump actions/checkout from 2 to 7",
      "status": "In review",
      "lane": "kustomize",
      "ageDays": 42,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "sourceos-continuum#6",
      "title": "chore(deps): bump docker/setup-qemu-action from 3.7.0 to 4.2.0",
      "status": "In review",
      "lane": "sourceos-continuum",
      "ageDays": 30,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "tritfabric#32",
      "title": "build(deps): bump the go_modules group across 2 directories with 1 update",
      "status": "In review",
      "lane": "tritfabric",
      "ageDays": 24,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "noetica-mcp#5",
      "title": "chore(deps): bump actions/setup-go from 6.5.0 to 7.0.0",
      "status": "In review",
      "lane": "noetica-mcp",
      "ageDays": 15,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "noetica-mcp#4",
      "title": "chore(deps): bump actions/setup-node from 5.0.0 to 7.0.0",
      "status": "In review",
      "lane": "noetica-mcp",
      "ageDays": 15,
      "risk": "high",
      "blocked": true
    },
    {
      "ref": "kustomize#6",
      "title": "Bump actions/setup-go from 4 to 7",
      "status": "In review",
      "lane": "kustomize",
      "ageDays": 14,
      "risk": "medium",
      "blocked": false
    },
    {
      "ref": "functional-model-surfaces#15",
      "title": "Bump actions/setup-python from 6.3.0 to 7.0.0",
      "status": "In review",
      "lane": "functional-model-surfaces",
      "ageDays": 13,
      "risk": "medium",
      "blocked": false
    }
  ],
  "gates": [
    {
      "name": "Evidence collected",
      "status": "pass",
      "detail": "Estate rollup across SocioProphet, SourceOS-Linux from live search evidence."
    },
    {
      "name": "Forecast has sufficient history",
      "status": "pass",
      "detail": "10 weekly throughput samples (minimum 6 to forecast)."
    },
    {
      "name": "Aging WIP within threshold",
      "status": "fail",
      "detail": "25 PR(s) older than 7d (threshold 10)."
    },
    {
      "name": "Board spec resolved",
      "status": "pass",
      "detail": "13 boards from /home/runner/work/socioprophet/socioprophet/.sociosphere/registry/board-spec.yaml."
    },
    {
      "name": "Backlog is prioritized (MoSCoW)",
      "status": "unverified",
      "detail": "No MoSCoW labels found on open issues — the backlog is unprioritized, so Must-share discipline cannot be assessed."
    }
  ],
  "boards": [
    "Portfolio Roadmap",
    "Spec, Ontology & Contracts",
    "Reasoning & Intelligence",
    "Governance & Control Plane",
    "SourceOS Base OS",
    "SociOS Managed Plane",
    "Model Surfaces (Labs)",
    "Agent Runtime & Terminal",
    "BearBrowser",
    "Platform & GitOps",
    "Product Surfaces",
    "Mesh & Orchestration",
    "Delivery Excellence"
  ]
} as const;
