// GENERATED by scripts/generate-delivery-snapshot.mjs — do not edit by hand.
// Regenerated by CI on merge to master so the dashboard cannot drift from what shipped.
// sourceMode 'live' at commit befb260.
import type { DeliverySnapshot } from '../features/delivery/contract';

export const deliverySnapshot: DeliverySnapshot = {
  "sourceMode": "live",
  "generatedAt": "2026-08-03T19:43:29.059Z",
  "commit": "befb260e369551bd1e7db2b3144400e0e21e577d",
  "workflowRun": null,
  "repo": "SocioProphet/socioprophet",
  "boundaryNotice": "Computed from merged PRs and issue events on SocioProphet/socioprophet over the last 14 days. Board columns are derived from that evidence, not read from a Projects board — per registry/board-spec.yaml, Projects is a render target, not the truth. Sprint commitment is a declared field and is marked as such.",
  "sprint": {
    "name": "Rolling 14-day window",
    "startedAt": "2026-07-20T19:43:25.185Z",
    "endsAt": "2026-08-03T19:43:29.059Z",
    "committed": 43,
    "completed": 43,
    "addedMidSprint": 0,
    "carriedOver": 0
  },
  "metrics": [
    {
      "id": "throughput",
      "label": "Throughput",
      "value": 43,
      "unit": "count",
      "basis": "measured",
      "evidence": "gh api repos/SocioProphet/socioprophet/pulls merged_at>=2026-07-20 base=master",
      "better": "up",
      "note": "PRs merged to master in the last 14 days."
    },
    {
      "id": "cycle-time",
      "label": "Median cycle time",
      "value": 0,
      "unit": "days",
      "basis": "measured",
      "evidence": "median(merged_at - created_at) over merged PRs",
      "better": "down",
      "note": "Open to merge, median across the window."
    },
    {
      "id": "wip",
      "label": "Work in progress",
      "value": 0,
      "unit": "count",
      "basis": "measured",
      "evidence": "gh api repos/SocioProphet/socioprophet/pulls state=open",
      "better": "down",
      "note": "Open pull requests right now."
    },
    {
      "id": "aging",
      "label": "Aging WIP",
      "value": 0,
      "unit": "count",
      "basis": "measured",
      "evidence": "open PRs older than 7d",
      "better": "down",
      "note": "Open PRs older than 7 days — the flow risk."
    },
    {
      "id": "issues-closed",
      "label": "Issues closed",
      "value": 63,
      "unit": "count",
      "basis": "measured",
      "evidence": "gh api repos/SocioProphet/socioprophet/issues state=closed since=2026-07-20",
      "better": "up",
      "note": "Issues closed in the last 14 days."
    },
    {
      "id": "issues-open",
      "label": "Open issues",
      "value": 8,
      "unit": "count",
      "basis": "measured",
      "evidence": "gh api repos/SocioProphet/socioprophet/issues state=open",
      "better": "down",
      "note": "Open issues touched in the window."
    }
  ],
  "columns": [
    {
      "name": "Open (issues)",
      "count": 8,
      "aging": 0
    },
    {
      "name": "In review (PRs)",
      "count": 0,
      "wipLimit": 10,
      "aging": 0
    },
    {
      "name": "Merged (14d)",
      "count": 43,
      "aging": 0
    },
    {
      "name": "Closed (14d)",
      "count": 63,
      "aging": 0
    }
  ],
  "items": [],
  "gates": [
    {
      "name": "Evidence collected",
      "status": "pass",
      "detail": "Snapshot computed from live merge and issue evidence."
    },
    {
      "name": "Aging WIP within threshold",
      "status": "pass",
      "detail": "0 PR(s) older than 7d (threshold 5)."
    },
    {
      "name": "WIP limit respected",
      "status": "pass",
      "detail": "0 open PR(s) against a limit of 10."
    }
  ],
  "boards": [
    "Portfolio Roadmap",
    "Spec, Ontology & Contracts",
    "Reasoning & Intelligence",
    "Governance & Control Plane"
  ]
} as const;
