insert into core.predicate_catalog (predicate_code, predicate_kind, label, value_type, semantic_family, description, source_standard)
values
  ('legal_name', 'attribute', 'Legal name', 'string', 'identity', 'Official legal name of the entity', 'internal'),
  ('alternate_name', 'attribute', 'Alternate name', 'string', 'identity', 'Alternative or alias name', 'internal'),
  ('registered_address', 'attribute', 'Registered address', 'json', 'location', 'Registered office or registered address', 'internal'),
  ('headquarters_address', 'attribute', 'Headquarters address', 'json', 'location', 'Headquarters or principal office address', 'internal'),
  ('country_of_incorporation', 'attribute', 'Country of incorporation', 'code', 'jurisdiction', 'Country of incorporation', 'internal'),
  ('country_of_domicile', 'attribute', 'Country of domicile', 'code', 'jurisdiction', 'Country of domicile or management location', 'internal'),
  ('legal_form', 'attribute', 'Legal form', 'code', 'classification', 'Legal form or ELF code', 'internal'),
  ('entity_status', 'attribute', 'Entity status', 'code', 'classification', 'Lifecycle status of entity', 'internal'),
  ('industry_code', 'attribute', 'Industry code', 'code', 'classification', 'Industry or sector code', 'internal'),
  ('nationality', 'attribute', 'Nationality', 'code', 'identity', 'Nationality for natural person', 'internal'),
  ('date_of_birth', 'attribute', 'Date of birth', 'date', 'identity', 'Date of birth or partial DOB', 'internal'),
  ('birth_place', 'attribute', 'Place of birth', 'json', 'identity', 'Place of birth', 'internal'),
  ('website', 'attribute', 'Website', 'string', 'contact', 'Website URL', 'internal'),
  ('email', 'attribute', 'Email', 'string', 'contact', 'Email address', 'internal'),
  ('remarks', 'attribute', 'Remarks', 'string', 'commentary', 'Narrative remarks or source comment', 'internal'),
  ('managing_lou', 'attribute', 'Managing LOU', 'string', 'provenance', 'LEI managing issuer / LOU', 'GLEIF'),
  ('validation_source', 'attribute', 'Validation source', 'string', 'provenance', 'Validation source category', 'GLEIF'),
  ('direct_parent_exception_reason', 'attribute', 'Direct parent exception reason', 'code', 'ownership', 'GLEIF reporting exception for direct parent', 'GLEIF'),
  ('ultimate_parent_exception_reason', 'attribute', 'Ultimate parent exception reason', 'code', 'ownership', 'GLEIF reporting exception for ultimate parent', 'GLEIF'),
  ('company_number', 'attribute', 'Company number', 'string', 'registry', 'Registry-local company number', 'Companies House'),
  ('notified_on', 'attribute', 'Notified on', 'date', 'registry', 'Date when registry was notified', 'Companies House'),
  ('appointed_on', 'attribute', 'Appointed on', 'date', 'registry', 'Date of appointment', 'Companies House'),
  ('resigned_on', 'attribute', 'Resigned on', 'date', 'registry', 'Date of resignation', 'Companies House'),
  ('direct_accounting_parent_of', 'relationship', 'Direct accounting parent of', 'null', 'ownership', 'GLEIF direct accounting-consolidating parent', 'GLEIF'),
  ('ultimate_accounting_parent_of', 'relationship', 'Ultimate accounting parent of', 'null', 'ownership', 'GLEIF ultimate accounting-consolidating parent', 'GLEIF'),
  ('owns', 'relationship', 'Owns', 'null', 'ownership', 'Ownership relationship', 'internal'),
  ('controls', 'relationship', 'Controls', 'null', 'control', 'Control relationship', 'internal'),
  ('beneficial_owner_of', 'relationship', 'Beneficial owner of', 'null', 'ownership', 'Beneficial ownership relationship', 'BODS'),
  ('officer_of', 'relationship', 'Officer of', 'null', 'governance', 'Officer appointment relationship', 'Companies House'),
  ('possible_same_as', 'relationship', 'Possible same as', 'null', 'resolution', 'Possible same-entity relation', 'internal'),
  ('not_same_as', 'relationship', 'Not same as', 'null', 'resolution', 'Negative resolution relation', 'internal')
on conflict (predicate_code) do nothing;
