name: gitleaks

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  scan:
    name: scan
    runs-on:
      - self-hosted
      - linux
      - x64
      - fedora
      - coreos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
